atwork-commander: atwork_commander::ControlImpl Class Reference
atwork_commander::ControlImpl Class Reference
Public Member Functions
void stateUpdate (RefboxState::ConstPtr msgPtr)
ControlImpl (string name)
void forward ()
Task generate (const string &task)
void stop ()
void start (vector< string > robots={})
void store (fs::path fileName)
void load (fs::path fileName)
Public Attributes
RefboxState state
Callback callback
string refbox
bool verbose = false
ros::Subscriber stateSub
Detailed Description
Definition at line 79 of file control.cpp.
Constructor & Destructor Documentation
atwork_commander::ControlImpl::ControlImpl (string name) inline
Definition at line 94 of file control.cpp.
References stateUpdate().
Member Function Documentation
void atwork_commander::ControlImpl::forward () inline
Definition at line 102 of file control.cpp.
References atwork_commander::call(), atwork_commander::ControlError::ControlError(), atwork_commander::ControlError::STATE_INVALID, and atwork_commander_msgs::stateName().
Referenced by atwork_commander::Control::forward().
Task atwork_commander::ControlImpl::generate (const string & task) inline
Definition at line 120 of file control.cpp.
References atwork_commander::call().
Referenced by atwork_commander::Control::generate().
void atwork_commander::ControlImpl::load (fs::path fileName) inline
Definition at line 190 of file control.cpp.
References atwork_commander::call(), atwork_commander::ControlError::ControlError(), and atwork_commander::ControlError::PATH_INVALID.
Referenced by atwork_commander::Control::load().
void atwork_commander::ControlImpl::start (vector< string > robots = {}) inline
Definition at line 146 of file control.cpp.
References atwork_commander::ControlError::ARGUMENT_INVALID, atwork_commander::call(), atwork_commander::ControlError::ControlError(), atwork_commander::ControlError::STATE_INVALID, and atwork_commander_msgs::stateName().
Referenced by atwork_commander::Control::start().
void atwork_commander::ControlImpl::stateUpdate (RefboxState::ConstPtr msgPtr) inline
Definition at line 88 of file control.cpp.
Referenced by ControlImpl().
void atwork_commander::ControlImpl::stop () inline
Definition at line 131 of file control.cpp.
References atwork_commander::call(), atwork_commander::ControlError::ControlError(), atwork_commander::ControlError::STATE_INVALID, and atwork_commander_msgs::stateName().
Referenced by atwork_commander::Control::stop().
void atwork_commander::ControlImpl::store (fs::path fileName) inline
Definition at line 171 of file control.cpp.
References atwork_commander::ControlError::ControlError(), and atwork_commander::ControlError::PATH_INVALID.
Referenced by atwork_commander::Control::store().
Member Data Documentation
Callback atwork_commander::ControlImpl::callback
Definition at line 82 of file control.cpp.
Referenced by atwork_commander::Control::stateUpdateCallback().
string atwork_commander::ControlImpl::refbox
Definition at line 83 of file control.cpp.
Referenced by atwork_commander::Control::refbox().
RefboxState atwork_commander::ControlImpl::state
Definition at line 81 of file control.cpp.
Referenced by atwork_commander::Control::state().
ros::Subscriber atwork_commander::ControlImpl::stateSub
Definition at line 86 of file control.cpp.
bool atwork_commander::ControlImpl::verbose = false
Definition at line 84 of file control.cpp.
Referenced by atwork_commander::Control::verbose().
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_core/src/control.cpp