atwork-commander: atwork_commander::RefboxUI Class Reference
atwork_commander::RefboxUI Class Reference
The Actual RVIZ Plugin.
#include <rviz_plugin.h>
Public Member Functions
RefboxUI (QWidget *parent=nullptr)
~RefboxUI ()
Private Attributes
MainVisGroup mainVG
TaskGenVisGroup taskGenVG
RobotVisGroup robotGenVG
ArenaVisGroup arenaGenVG
ros::NodeHandle nh
std::shared_ptr< atwork_commander::Control > control_ptr
Detailed Description
The Actual RVIZ Plugin.
This is the class that gets registered an exported as a RVIZ Plugin. It itself provides a stacked widget to show different VisGroups and a refresh Button to update the currently selected VisGruop.
Definition at line 760 of file rviz_plugin.h.
Constructor & Destructor Documentation
atwork_commander::RefboxUI::RefboxUI (QWidget * parent = nullptr)
init communication to core
qt
Definition at line 9 of file rviz_plugin.cpp.
References arenaGenVG, control_ptr, atwork_commander::VisGroup::getLayout(), mainVG, refboxName, atwork_commander::MainVisGroup::registerSubclass(), robotGenVG, atwork_commander::MainVisGroup::setControlPtr(), and taskGenVG.
atwork_commander::RefboxUI::~RefboxUI () inline
Definition at line 774 of file rviz_plugin.h.
Member Data Documentation
ArenaVisGroup atwork_commander::RefboxUI::arenaGenVG private
Definition at line 766 of file rviz_plugin.h.
Referenced by RefboxUI().
std::shared_ptr<atwork_commander::Control> atwork_commander::RefboxUI::control_ptr private
Definition at line 770 of file rviz_plugin.h.
Referenced by RefboxUI().
MainVisGroup atwork_commander::RefboxUI::mainVG private
Definition at line 763 of file rviz_plugin.h.
Referenced by RefboxUI().
ros::NodeHandle atwork_commander::RefboxUI::nh private
Definition at line 768 of file rviz_plugin.h.
RobotVisGroup atwork_commander::RefboxUI::robotGenVG private
Definition at line 765 of file rviz_plugin.h.
Referenced by RefboxUI().
TaskGenVisGroup atwork_commander::RefboxUI::taskGenVG private
Definition at line 764 of file rviz_plugin.h.
Referenced by RefboxUI().
The documentation for this class was generated from the following files:
/home/travis/build/steup/atwork-commander/atwork_commander_gui/src/rviz_plugin.h
/home/travis/build/steup/atwork-commander/atwork_commander_gui/src/rviz_plugin.cpp