atwork-commander: atwork_commander::task_generator::GeneratorPluginInterface Class Reference
atwork_commander::task_generator::GeneratorPluginInterface Class Reference abstract
#include <GeneratorPluginInterface.h>
Public Types
using Task = ::atwork_commander_msgs::Task
Public Member Functions
virtual ~GeneratorPluginInterface ()
virtual void onInit (const std::string &arenaConfig, const std::string &taskConfig)=0
virtual Task generate (const std::string &taskName)=0
virtual bool check (const Task &task) const =0
virtual ConfigParserInterface & config ()=0
Detailed Description
Definition at line 14 of file GeneratorPluginInterface.h.
Member Typedef Documentation
using atwork_commander::task_generator::GeneratorPluginInterface::Task = ::atwork_commander_msgs::Task
Definition at line 16 of file GeneratorPluginInterface.h.
Constructor & Destructor Documentation
virtual atwork_commander::task_generator::GeneratorPluginInterface::~GeneratorPluginInterface () inline virtual
Definition at line 17 of file GeneratorPluginInterface.h.
References check(), config(), generate(), and onInit().
Member Function Documentation
virtual bool atwork_commander::task_generator::GeneratorPluginInterface::check (const Task & task) const pure virtual
Implemented in atwork_commander::task_generator::jurek::Generator, and atwork_commander::task_generator::simple::Generator.
Referenced by ~GeneratorPluginInterface().
virtual ConfigParserInterface& atwork_commander::task_generator::GeneratorPluginInterface::config () pure virtual
Implemented in atwork_commander::task_generator::jurek::Generator, and atwork_commander::task_generator::simple::Generator.
Referenced by ~GeneratorPluginInterface().
virtual Task atwork_commander::task_generator::GeneratorPluginInterface::generate (const std::string & taskName) pure virtual
Implemented in atwork_commander::task_generator::jurek::Generator, and atwork_commander::task_generator::simple::Generator.
Referenced by ~GeneratorPluginInterface().
virtual void atwork_commander::task_generator::GeneratorPluginInterface::onInit (const std::string & arenaConfig, const std::string & taskConfig) pure virtual
Implemented in atwork_commander::task_generator::jurek::Generator, and atwork_commander::task_generator::simple::Generator.
Referenced by ~GeneratorPluginInterface().
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_gen/include/atwork_commander_gen/GeneratorPluginInterface.h