atwork-commander: atwork_commander::TaskGenVisGroup Class Reference
atwork_commander::TaskGenVisGroup Class Reference
Qt widget displaying task generator information.
#include <rviz_plugin.h>
Public Slots
QString printArenaStateList (std::vector< atwork_commander_msgs::Workstation > ws_list, bool print_empty_container=true)
virtual void generateTask ()
generate on push
virtual void update () override
Reimplementation of the Qt fucntion - updates the UI.
Public Slots inherited from atwork_commander::VisGroup
virtual void update ()=0
Causes the Widget to update itself.
Public Member Functions
TaskGenVisGroup (QWidget *parent=new QWidget())
virtual ~TaskGenVisGroup ()
virtual void wire (bool make_connections=true)
wire connects and disconnect ALL existing Signal-Slots Connections
virtual bool hasFocus () override
Disable update of the Widget if hasFocus returns true.
Public Member Functions inherited from atwork_commander::VisGroup
VisGroup (QWidget *parent=nullptr)
virtual ~VisGroup ()
virtual void setControlPtr (std::shared_ptr< atwork_commander::Control > new_control_ptr)
virtual QWidget * getWidget ()
virtual QLayout * getLayout ()
Private Attributes
std::unique_ptr< QLabel > taskListLabel
std::unique_ptr< QComboBox > taskListCombo
std::unique_ptr< QLabel > prepTimeLabel
std::unique_ptr< QLineEdit > prepTimeLineEdit
std::unique_ptr< QLabel > runTimeLabel
std::unique_ptr< QLineEdit > runTimeLineEdit
std::unique_ptr< QHBoxLayout > basicHBox
std::unique_ptr< QPushButton > generateButton
std::unique_ptr< QPushButton > loadButton
std::unique_ptr< QHBoxLayout > buttonHBox
std::unique_ptr< QLabel > arenaStartLabel
std::unique_ptr< QTextEdit > arenaStartText
std::unique_ptr< QVBoxLayout > arenaStartVBox
std::unique_ptr< QLabel > arenaEndLabel
std::unique_ptr< QTextEdit > arenaEndText
std::unique_ptr< QVBoxLayout > arenaEndVBox
std::unique_ptr< QHBoxLayout > arenaHBox
std::unique_ptr< QLineEdit > pptCavatiesLineEdit
Additional Inherited Members
Protected Attributes inherited from atwork_commander::VisGroup
QWidget * self = nullptr
QFormLayout * layout = nullptr
QMessageBox * message = nullptr
std::shared_ptr< atwork_commander::Control > control_ptr
Detailed Description
Qt widget displaying task generator information.
Definition at line 264 of file rviz_plugin.h.
Constructor & Destructor Documentation
atwork_commander::TaskGenVisGroup::TaskGenVisGroup (QWidget * parent = new QWidget()) inline
Definition at line 290 of file rviz_plugin.h.
References atwork_commander::VisGroup::layout, and atwork_commander::VisGroup::update().
virtual atwork_commander::TaskGenVisGroup::~TaskGenVisGroup () inline virtual
Definition at line 369 of file rviz_plugin.h.
Member Function Documentation
virtual void atwork_commander::TaskGenVisGroup::generateTask () inline virtual slot
generate on push
Definition at line 479 of file rviz_plugin.h.
References atwork_commander::VisGroup::control_ptr, and atwork_commander_msgs::objectName().
virtual bool atwork_commander::TaskGenVisGroup::hasFocus () inline override virtual
Disable update of the Widget if hasFocus returns true.
Any subGroup can disable being updated by returning true. ie when we are on a page that allows the user to create new instances and updating would make the userinput disappear.
Implements atwork_commander::VisGroup.
Definition at line 398 of file rviz_plugin.h.
QString atwork_commander::TaskGenVisGroup::printArenaStateList (std::vector< atwork_commander_msgs::Workstation > ws_list, bool print_empty_container = true) inline slot
Definition at line 413 of file rviz_plugin.h.
References atwork_commander_msgs::objectName().
virtual void atwork_commander::TaskGenVisGroup::update () inline override virtual slot
Reimplementation of the Qt fucntion - updates the UI.
Get the up to date informationi from the worldmodel and display it in the UI
Definition at line 520 of file rviz_plugin.h.
virtual void atwork_commander::TaskGenVisGroup::wire (bool make_connections = true) inline virtual
wire connects and disconnect ALL existing Signal-Slots Connections
A simple wire() call establishes all connections, a wire(false) call disables all connections. This is usefull, so that when updating the UI there wont be a number of writeFunctions called, "updating" the values, that have just been read from the worldmodel.
Definition at line 379 of file rviz_plugin.h.
References atwork_commander::VisGroup::update().
Member Data Documentation
std::unique_ptr<QLabel> atwork_commander::TaskGenVisGroup::arenaEndLabel private
Definition at line 282 of file rviz_plugin.h.
std::unique_ptr<QTextEdit> atwork_commander::TaskGenVisGroup::arenaEndText private
Definition at line 283 of file rviz_plugin.h.
std::unique_ptr<QVBoxLayout> atwork_commander::TaskGenVisGroup::arenaEndVBox private
Definition at line 284 of file rviz_plugin.h.
std::unique_ptr<QHBoxLayout> atwork_commander::TaskGenVisGroup::arenaHBox private
Definition at line 285 of file rviz_plugin.h.
std::unique_ptr<QLabel> atwork_commander::TaskGenVisGroup::arenaStartLabel private
Definition at line 279 of file rviz_plugin.h.
std::unique_ptr<QTextEdit> atwork_commander::TaskGenVisGroup::arenaStartText private
Definition at line 280 of file rviz_plugin.h.
std::unique_ptr<QVBoxLayout> atwork_commander::TaskGenVisGroup::arenaStartVBox private
Definition at line 281 of file rviz_plugin.h.
std::unique_ptr<QHBoxLayout> atwork_commander::TaskGenVisGroup::basicHBox private
Definition at line 273 of file rviz_plugin.h.
std::unique_ptr<QHBoxLayout> atwork_commander::TaskGenVisGroup::buttonHBox private
Definition at line 277 of file rviz_plugin.h.
std::unique_ptr<QPushButton> atwork_commander::TaskGenVisGroup::generateButton private
Definition at line 275 of file rviz_plugin.h.
std::unique_ptr<QPushButton> atwork_commander::TaskGenVisGroup::loadButton private
Definition at line 276 of file rviz_plugin.h.
std::unique_ptr<QLineEdit> atwork_commander::TaskGenVisGroup::pptCavatiesLineEdit private
Definition at line 287 of file rviz_plugin.h.
std::unique_ptr<QLabel> atwork_commander::TaskGenVisGroup::prepTimeLabel private
Definition at line 269 of file rviz_plugin.h.
std::unique_ptr<QLineEdit> atwork_commander::TaskGenVisGroup::prepTimeLineEdit private
Definition at line 270 of file rviz_plugin.h.
std::unique_ptr<QLabel> atwork_commander::TaskGenVisGroup::runTimeLabel private
Definition at line 271 of file rviz_plugin.h.
std::unique_ptr<QLineEdit> atwork_commander::TaskGenVisGroup::runTimeLineEdit private
Definition at line 272 of file rviz_plugin.h.
std::unique_ptr<QComboBox> atwork_commander::TaskGenVisGroup::taskListCombo private
Definition at line 268 of file rviz_plugin.h.
std::unique_ptr<QLabel> atwork_commander::TaskGenVisGroup::taskListLabel private
Definition at line 267 of file rviz_plugin.h.
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_gui/src/rviz_plugin.h