atwork-commander: atwork_commander::VisGroup Class Reference
atwork_commander::VisGroup Class Reference abstract
Abstract Base Class VisGroup.
#include <rviz_plugin.h>
Public Slots
virtual void update ()=0
Causes the Widget to update itself.
Public Member Functions
VisGroup (QWidget *parent=nullptr)
virtual ~VisGroup ()
virtual void setControlPtr (std::shared_ptr< atwork_commander::Control > new_control_ptr)
virtual QWidget * getWidget ()
virtual QLayout * getLayout ()
virtual bool hasFocus ()=0
Disable update of the Widget if hasFocus returns true.
Protected Attributes
QWidget * self = nullptr
QFormLayout * layout = nullptr
QMessageBox * message = nullptr
std::shared_ptr< atwork_commander::Control > control_ptr
Detailed Description
Abstract Base Class VisGroup.
This baseclas specifies the interface for subclasses that should work within the RefboxUI and provides a number of conviences (fucntions and members)
Definition at line 41 of file rviz_plugin.h.
Constructor & Destructor Documentation
atwork_commander::VisGroup::VisGroup (QWidget * parent = nullptr) inline
Definition at line 56 of file rviz_plugin.h.
virtual atwork_commander::VisGroup::~VisGroup () inline virtual
Definition at line 65 of file rviz_plugin.h.
References layout, and message.
Member Function Documentation
virtual QLayout* atwork_commander::VisGroup::getLayout () inline virtual
Definition at line 84 of file rviz_plugin.h.
References hasFocus(), layout, and update().
Referenced by atwork_commander::RefboxUI::RefboxUI().
virtual QWidget* atwork_commander::VisGroup::getWidget () inline virtual
Definition at line 83 of file rviz_plugin.h.
Referenced by atwork_commander::MainVisGroup::registerSubclass().
virtual bool atwork_commander::VisGroup::hasFocus () pure virtual
Disable update of the Widget if hasFocus returns true.
Any subGroup can disable being updated by returning true. ie when we are on a page that allows the user to create new instances and updating would make the userinput disappear.
Implemented in atwork_commander::ArenaVisGroup, atwork_commander::RobotVisGroup, atwork_commander::TaskGenVisGroup, and atwork_commander::MainVisGroup.
Referenced by getLayout().
virtual void atwork_commander::VisGroup::setControlPtr (std::shared_ptr< atwork_commander::Control > new_control_ptr) inline virtual
Reimplemented in atwork_commander::MainVisGroup.
Definition at line 75 of file rviz_plugin.h.
virtual void atwork_commander::VisGroup::update () pure virtual slot
Causes the Widget to update itself.
When update is being called the subGroup gets a chance to collect the current data from the worldmodel.
Implemented in atwork_commander::MainVisGroup.
Referenced by atwork_commander::ArenaVisGroup::ArenaVisGroup(), getLayout(), atwork_commander::RobotVisGroup::RobotVisGroup(), atwork_commander::TaskGenVisGroup::TaskGenVisGroup(), atwork_commander::TaskGenVisGroup::wire(), and atwork_commander::RobotVisGroup::wire().
Member Data Documentation
std::shared_ptr<atwork_commander::Control> atwork_commander::VisGroup::control_ptr protected
Definition at line 53 of file rviz_plugin.h.
Referenced by atwork_commander::TaskGenVisGroup::generateTask(), and atwork_commander::MainVisGroup::setControlPtr().
QFormLayout* atwork_commander::VisGroup::layout = nullptr protected
Definition at line 48 of file rviz_plugin.h.
Referenced by atwork_commander::ArenaVisGroup::ArenaVisGroup(), getLayout(), atwork_commander::MainVisGroup::MainVisGroup(), atwork_commander::RobotVisGroup::RobotVisGroup(), atwork_commander::TaskGenVisGroup::TaskGenVisGroup(), and ~VisGroup().
QMessageBox* atwork_commander::VisGroup::message = nullptr protected
Definition at line 51 of file rviz_plugin.h.
Referenced by ~VisGroup().
QWidget* atwork_commander::VisGroup::self = nullptr protected
Definition at line 46 of file rviz_plugin.h.
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_gui/src/rviz_plugin.h