atwork-commander: atwork_commander::ConfigParserInterface Class Reference
atwork_commander::ConfigParserInterface Class Reference abstract
#include <ConfigParserInterface.h>
Public Member Functions
void reload (const std::string &arenaConfig, const std::string &taskConfig)
const std::string & taskConfig () const
const std::string & arenaConfig () const
virtual const TaskDefinitions & tasks () const =0
virtual const ArenaDescription & arena () const =0
Protected Member Functions
virtual void update ()=0
Private Attributes
std::string mTaskConfig
std::string mArenaConfig
Detailed Description
Definition at line 69 of file ConfigParserInterface.h.
Member Function Documentation
virtual const ArenaDescription& atwork_commander::ConfigParserInterface::arena () const pure virtual
Implemented in atwork_commander::task_generator::DefaultConfigParser.
Referenced by main().
const std::string& atwork_commander::ConfigParserInterface::arenaConfig () const inline
Definition at line 92 of file ConfigParserInterface.h.
References operator<<().
void atwork_commander::ConfigParserInterface::reload (const std::string & arenaConfig, const std::string & taskConfig) inline
Definition at line 76 of file ConfigParserInterface.h.
Referenced by atwork_commander::task_generator::simple::Generator::onInit(), and atwork_commander::task_generator::jurek::Generator::onInit().
const std::string& atwork_commander::ConfigParserInterface::taskConfig () const inline
Definition at line 91 of file ConfigParserInterface.h.
virtual const TaskDefinitions& atwork_commander::ConfigParserInterface::tasks () const pure virtual
Implemented in atwork_commander::task_generator::DefaultConfigParser.
Referenced by main().
virtual void atwork_commander::ConfigParserInterface::update () protected pure virtual
Implemented in atwork_commander::task_generator::DefaultConfigParser.
Member Data Documentation
std::string atwork_commander::ConfigParserInterface::mArenaConfig private
Definition at line 72 of file ConfigParserInterface.h.
std::string atwork_commander::ConfigParserInterface::mTaskConfig private
Definition at line 71 of file ConfigParserInterface.h.
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_gen/include/atwork_commander_gen/ConfigParserInterface.h