atwork-commander: atwork_commander::com_plugin::ros::TaskArenaCentric Class Reference
atwork_commander::com_plugin::ros::TaskArenaCentric Class Reference
Public Member Functions
TaskArenaCentric ()
virtual ~TaskArenaCentric ()
virtual void sendTask (atwork_commander_msgs::Task task)
virtual void onInit (::ros::NodeHandle roshandle)
Public Member Functions inherited from atwork_commander::com_plugin::Base
virtual ~Base ()
void initialize (ros::NodeHandle roshandle, robot_state_fct_t rsf)
Initalize the global variables.
Private Member Functions
void receiveRobotStateClb (const atwork_commander_msgs::RobotState::ConstPtr &msg)
Private Attributes
::ros::NodeHandle rh
::ros::Subscriber robot_state_sub
::ros::Publisher send_task_pub
Additional Inherited Members
Protected Member Functions inherited from atwork_commander::com_plugin::Base
virtual void onInit (ros::NodeHandle roshandle)
In this function the plugIn can do some initialisation depending on a ROS NodeHandle.
void sendRobotState (atwork_commander_msgs::RobotState robot_state)
Detailed Description
Definition at line 9 of file ros_com_arena_centric.cpp.
Constructor & Destructor Documentation
atwork_commander::com_plugin::ros::TaskArenaCentric::TaskArenaCentric () inline
Definition at line 17 of file ros_com_arena_centric.cpp.
virtual atwork_commander::com_plugin::ros::TaskArenaCentric::~TaskArenaCentric () inline virtual
Definition at line 18 of file ros_com_arena_centric.cpp.
Member Function Documentation
virtual void atwork_commander::com_plugin::ros::TaskArenaCentric::onInit (::ros::NodeHandle roshandle) inline virtual
Definition at line 24 of file ros_com_arena_centric.cpp.
References receiveRobotStateClb().
void atwork_commander::com_plugin::ros::TaskArenaCentric::receiveRobotStateClb (const atwork_commander_msgs::RobotState::ConstPtr & msg) inline private
Definition at line 32 of file ros_com_arena_centric.cpp.
References PLUGINLIB_EXPORT_CLASS(), and atwork_commander::com_plugin::Base::sendRobotState().
Referenced by onInit().
virtual void atwork_commander::com_plugin::ros::TaskArenaCentric::sendTask (atwork_commander_msgs::Task task) inline virtual
Implements atwork_commander::com_plugin::Base.
Definition at line 20 of file ros_com_arena_centric.cpp.
Member Data Documentation
::ros::NodeHandle atwork_commander::com_plugin::ros::TaskArenaCentric::rh private
Definition at line 11 of file ros_com_arena_centric.cpp.
::ros::Subscriber atwork_commander::com_plugin::ros::TaskArenaCentric::robot_state_sub private
Definition at line 13 of file ros_com_arena_centric.cpp.
::ros::Publisher atwork_commander::com_plugin::ros::TaskArenaCentric::send_task_pub private
Definition at line 14 of file ros_com_arena_centric.cpp.
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_com/src/ros_com_arena_centric.cpp