atwork-commander: atwork_commander::StateTracker Class Reference
atwork_commander::StateTracker Class Reference
Public Member Functions
StateTracker (ros::NodeHandle nh, TaskGenerator &taskGen)
~StateTracker ()
Private Member Functions
void taskUpdate (const ros::TimerEvent &e)
void stateUpdate ()
bool notInState (std::vector< uint8_t > states) const
bool inState (std::vector< uint8_t > states) const
void publishUpdate (const ros::TimerEvent &e) const
void receiveRobotStateClb (const atwork_commander_msgs::RobotState::ConstPtr &msg)
bool startTask (atwork_commander_msgs::StartTask::Request &req, atwork_commander_msgs::StartTask::Response &res)
bool generateTask (atwork_commander_msgs::GenerateTask::Request &req, atwork_commander_msgs::GenerateTask::Response &res)
bool loadTask (atwork_commander_msgs::LoadTask::Request &req, atwork_commander_msgs::LoadTask::Response &res)
bool externalStateUpdate (atwork_commander_msgs::StateUpdate::Request &req, atwork_commander_msgs::StateUpdate::Response &res)
Static Private Member Functions
static std::string state2string (uint8_t state)
Private Attributes
ros::NodeHandle m_nh
double m_robot_timeout = 1.0
double m_publish_frequency = 1.0
TaskGenerator & m_task_gen
State m_state
bool m_checked = false
bool m_debug = false
ros::Publisher m_send_task_pub
ros::Publisher m_state_pub
ros::Subscriber m_robot_state_sub
ros::ServiceServer m_start_task_service
ros::ServiceServer m_generate_task_service
ros::ServiceServer m_load_task_service
ros::ServiceServer m_state_update_service
ros::Timer m_publish_timer
ros::Timer m_robot_timer
ros::Timer m_task_timer
Detailed Description
Definition at line 35 of file atwork_refbox_ros_node.cpp.
Constructor & Destructor Documentation
atwork_commander::StateTracker::StateTracker (ros::NodeHandle nh, TaskGenerator & taskGen) inline
Definition at line 68 of file atwork_refbox_ros_node.cpp.
References externalStateUpdate(), generateTask(), loadTask(), publishUpdate(), receiveRobotStateClb(), and startTask().
atwork_commander::StateTracker::~StateTracker () inline
Definition at line 98 of file atwork_refbox_ros_node.cpp.
Member Function Documentation
bool atwork_commander::StateTracker::externalStateUpdate (atwork_commander_msgs::StateUpdate::Request & req, atwork_commander_msgs::StateUpdate::Response & res) inline private
Definition at line 260 of file atwork_refbox_ros_node.cpp.
References stateUpdate().
Referenced by StateTracker().
bool atwork_commander::StateTracker::generateTask (atwork_commander_msgs::GenerateTask::Request & req, atwork_commander_msgs::GenerateTask::Response & res) inline private
Definition at line 211 of file atwork_refbox_ros_node.cpp.
References atwork_commander::TaskGenerator::check(), inState(), m_task_gen, and stateUpdate().
Referenced by StateTracker().
bool atwork_commander::StateTracker::inState (std::vector< uint8_t > states) const inline private
Definition at line 154 of file atwork_refbox_ros_node.cpp.
Referenced by generateTask(), loadTask(), and publishUpdate().
bool atwork_commander::StateTracker::loadTask (atwork_commander_msgs::LoadTask::Request & req, atwork_commander_msgs::LoadTask::Response & res) inline private
Definition at line 238 of file atwork_refbox_ros_node.cpp.
References atwork_commander::TaskGenerator::check(), inState(), and stateUpdate().
Referenced by StateTracker().
bool atwork_commander::StateTracker::notInState (std::vector< uint8_t > states) const inline private
Definition at line 149 of file atwork_refbox_ros_node.cpp.
Referenced by startTask().
void atwork_commander::StateTracker::publishUpdate (const ros::TimerEvent & e) const inline private
Definition at line 160 of file atwork_refbox_ros_node.cpp.
References inState(), and state2string().
Referenced by StateTracker().
void atwork_commander::StateTracker::receiveRobotStateClb (const atwork_commander_msgs::RobotState::ConstPtr & msg) inline private
Definition at line 170 of file atwork_refbox_ros_node.cpp.
References stateUpdate().
Referenced by StateTracker().
bool atwork_commander::StateTracker::startTask (atwork_commander_msgs::StartTask::Request & req, atwork_commander_msgs::StartTask::Response & res) inline private
Definition at line 181 of file atwork_refbox_ros_node.cpp.
References notInState(), and stateUpdate().
Referenced by StateTracker().
static std::string atwork_commander::StateTracker::state2string (uint8_t state) inline static private
Definition at line 37 of file atwork_refbox_ros_node.cpp.
Referenced by publishUpdate(), and stateUpdate().
void atwork_commander::StateTracker::stateUpdate () inline private
Definition at line 106 of file atwork_refbox_ros_node.cpp.
References m_checked, state2string(), and taskUpdate().
Referenced by externalStateUpdate(), generateTask(), loadTask(), receiveRobotStateClb(), startTask(), and taskUpdate().
void atwork_commander::StateTracker::taskUpdate (const ros::TimerEvent & e) inline private
Definition at line 102 of file atwork_refbox_ros_node.cpp.
References stateUpdate().
Referenced by stateUpdate().
Member Data Documentation
bool atwork_commander::StateTracker::m_checked = false private
Definition at line 53 of file atwork_refbox_ros_node.cpp.
Referenced by stateUpdate().
bool atwork_commander::StateTracker::m_debug = false private
Definition at line 54 of file atwork_refbox_ros_node.cpp.
ros::ServiceServer atwork_commander::StateTracker::m_generate_task_service private
Definition at line 60 of file atwork_refbox_ros_node.cpp.
ros::ServiceServer atwork_commander::StateTracker::m_load_task_service private
Definition at line 61 of file atwork_refbox_ros_node.cpp.
ros::NodeHandle atwork_commander::StateTracker::m_nh private
Definition at line 48 of file atwork_refbox_ros_node.cpp.
double atwork_commander::StateTracker::m_publish_frequency = 1.0 private
Definition at line 50 of file atwork_refbox_ros_node.cpp.
ros::Timer atwork_commander::StateTracker::m_publish_timer private
Definition at line 63 of file atwork_refbox_ros_node.cpp.
ros::Subscriber atwork_commander::StateTracker::m_robot_state_sub private
Definition at line 58 of file atwork_refbox_ros_node.cpp.
double atwork_commander::StateTracker::m_robot_timeout = 1.0 private
Definition at line 49 of file atwork_refbox_ros_node.cpp.
ros::Timer atwork_commander::StateTracker::m_robot_timer private
Definition at line 64 of file atwork_refbox_ros_node.cpp.
ros::Publisher atwork_commander::StateTracker::m_send_task_pub private
Definition at line 56 of file atwork_refbox_ros_node.cpp.
ros::ServiceServer atwork_commander::StateTracker::m_start_task_service private
Definition at line 59 of file atwork_refbox_ros_node.cpp.
State atwork_commander::StateTracker::m_state private
Definition at line 52 of file atwork_refbox_ros_node.cpp.
ros::Publisher atwork_commander::StateTracker::m_state_pub private
Definition at line 57 of file atwork_refbox_ros_node.cpp.
ros::ServiceServer atwork_commander::StateTracker::m_state_update_service private
Definition at line 62 of file atwork_refbox_ros_node.cpp.
TaskGenerator& atwork_commander::StateTracker::m_task_gen private
Definition at line 51 of file atwork_refbox_ros_node.cpp.
Referenced by generateTask().
ros::Timer atwork_commander::StateTracker::m_task_timer private
Definition at line 65 of file atwork_refbox_ros_node.cpp.
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_core/src/atwork_refbox_ros_node.cpp