atwork-commander: atwork_commander::task_generator::DefaultConfigParser Class Reference
atwork_commander::task_generator::DefaultConfigParser Class Reference
#include <DefaultConfigParser.h>
Public Member Functions
virtual const TaskDefinitions & tasks () const
virtual const ArenaDescription & arena () const
Public Member Functions inherited from atwork_commander::ConfigParserInterface
void reload (const std::string &arenaConfig, const std::string &taskConfig)
const std::string & taskConfig () const
const std::string & arenaConfig () const
Protected Member Functions
virtual void update ()
Protected Attributes
TaskDefinitions mTasks
ArenaDescription mArena
Detailed Description
Definition at line 8 of file DefaultConfigParser.h.
Member Function Documentation
virtual const ArenaDescription& atwork_commander::task_generator::DefaultConfigParser::arena () const inline virtual
Implements atwork_commander::ConfigParserInterface.
Definition at line 15 of file DefaultConfigParser.h.
References mArena.
Referenced by atwork_commander::task_generator::simple::Generator::onInit(), and atwork_commander::task_generator::jurek::Generator::onInit().
virtual const TaskDefinitions& atwork_commander::task_generator::DefaultConfigParser::tasks () const inline virtual
Implements atwork_commander::ConfigParserInterface.
Definition at line 14 of file DefaultConfigParser.h.
References mTasks.
void atwork_commander::task_generator::DefaultConfigParser::update () protected virtual
Implements atwork_commander::ConfigParserInterface.
Definition at line 224 of file DefaultConfigParser.cpp.
References atwork_commander::task_generator::filterObjects(), atwork_commander::task_generator::readArenaDefinition(), and atwork_commander::task_generator::readTaskList().
Member Data Documentation
ArenaDescription atwork_commander::task_generator::DefaultConfigParser::mArena protected
Definition at line 11 of file DefaultConfigParser.h.
Referenced by arena().
TaskDefinitions atwork_commander::task_generator::DefaultConfigParser::mTasks protected
Definition at line 10 of file DefaultConfigParser.h.
Referenced by tasks().
The documentation for this class was generated from the following files:
/home/travis/build/steup/atwork-commander/atwork_commander_gen/include/atwork_commander_gen/DefaultConfigParser.h
/home/travis/build/steup/atwork-commander/atwork_commander_gen/src/DefaultConfigParser.cpp