atwork-commander: atwork_commander::TaskGenerator Class Reference
atwork_commander::TaskGenerator Class Reference
#include <TaskGenerator.h>
Public Types
using Task = atwork_commander_msgs::Task
Public Member Functions
TaskGenerator (const std::string &arenaConfig, const std::string &taskConfig, const std::string &pluginConfig)
Task operator() (const std::string &taskName)
Generate new randomized task based on task definition.
bool check (const Task &task) const
Check task for basic soundness.
ConfigParserInterface & config ()
Private Types
using GeneratorPlugin = task_generator::GeneratorPluginInterface
using GeneratorPluginPtr = std::shared_ptr< GeneratorPlugin >
Private Attributes
GeneratorPluginPtr mImpl
Detailed Description
Definition at line 16 of file TaskGenerator.h.
Member Typedef Documentation
using atwork_commander::TaskGenerator::GeneratorPlugin = task_generator::GeneratorPluginInterface private
Definition at line 18 of file TaskGenerator.h.
using atwork_commander::TaskGenerator::GeneratorPluginPtr = std::shared_ptr<GeneratorPlugin> private
Definition at line 19 of file TaskGenerator.h.
using atwork_commander::TaskGenerator::Task = atwork_commander_msgs::Task
Definition at line 23 of file TaskGenerator.h.
Constructor & Destructor Documentation
atwork_commander::TaskGenerator::TaskGenerator (const std::string & arenaConfig, const std::string & taskConfig, const std::string & pluginConfig)
Definition at line 14 of file TaskGenerator.cpp.
Member Function Documentation
bool atwork_commander::TaskGenerator::check (const Task & task) const
Check task for basic soundness.
Parameters
task The task to check
Returns
true if sound, false otherwise
Exceptions
None
Definition at line 25 of file TaskGenerator.cpp.
Referenced by atwork_commander::StateTracker::generateTask(), atwork_commander::StateTracker::loadTask(), and main().
ConfigParserInterface & atwork_commander::TaskGenerator::config ()
Definition at line 26 of file TaskGenerator.cpp.
Referenced by main().
TaskGenerator::Task atwork_commander::TaskGenerator::operator() (const std::string & taskName)
Generate new randomized task based on task definition.
Parameters
taskName The name of the task as defined by the supplied TaskDefinitions
Returns
Task instance ready to be transmitted
Exceptions
std::runtime_error if something goes wrong
Definition at line 23 of file TaskGenerator.cpp.
Member Data Documentation
GeneratorPluginPtr atwork_commander::TaskGenerator::mImpl private
Definition at line 20 of file TaskGenerator.h.
The documentation for this class was generated from the following files:
/home/travis/build/steup/atwork-commander/atwork_commander_gen/include/atwork_commander_gen/TaskGenerator.h
/home/travis/build/steup/atwork-commander/atwork_commander_gen/src/TaskGenerator.cpp