atwork-commander: atwork_commander::task_generator::simple::Generator Class Reference
atwork_commander::task_generator::simple::Generator Class Reference
Task Generation Implementation.
Public Member Functions
virtual void onInit (const std::string &arenaConfig, const std::string &taskConfig)
virtual bool check (const Task &task) const
virtual Task generate (const std::string &taskName)
virtual ConfigParserInterface & config ()
Public Member Functions inherited from atwork_commander::task_generator::GeneratorPluginInterface
virtual ~GeneratorPluginInterface ()
Private Member Functions
auto extractObjectTypes (const string &task)
void sanityCheck (std::string task, const vector< ObjectType > &availableObjects)
void sanityCheck ()
vector< TablePtr > extractTablesByTypes (vector< string > types)
uint16_t toContainerType (const Object &o)
uint16_t toCavityType (const Object &o)
uint16_t toColoredObjectType (const Object &o)
uint16_t toObjectType (const Object &o)
atwork_commander_msgs::Object toTaskObject (const Object &o)
Task toTask (const vector< Object > &objects)
template<typename T >
T & uniqueSelect (typename vector< T >::iterator start, typename vector< T >::iterator &end)
vector< Object * > generateCavities (TaskDefinition &def, vector< ObjectType > &availableCavities, vector< Object >::iterator start)
vector< Object * > generateContainers (TaskDefinition &def, vector< ObjectType > &availableObjects, vector< Object >::iterator start)
vector< Object * > generateObjects (TaskDefinition &def, vector< ObjectType * > availableObjects, vector< Object >::iterator start, size_t objectCount, size_t decoyCount)
vector< Object * > generateObjects (TaskDefinition &def, vector< ObjectType > availableObjects, vector< Object >::iterator start, size_t objectCount=1, size_t decoyCount=0)
template<typename F >
vector< Object * > generateObjects (TaskDefinition &def, vector< ObjectType > availableObjects, vector< Object >::iterator start, size_t objectCount, size_t decoyCount, F &&filter)
void place (TaskDefinition &def, Object &object, vector< string > tableTypes)
void place (TaskDefinition &def, Object &object, Object &container)
void pick (TaskDefinition &def, Object &object, vector< string > tableTypes)
Task generateImpl (const string &taskName)
Static Private Member Functions
static auto extractCavities (const ArenaDescription &arena)
template<typename T >
static vector< T * > toPtr (typename vector< T >::iterator start, typename vector< T >::iterator end)
static void cleanTypes (vector< ObjectType > &types)
Private Attributes
default_random_engine mRand
DefaultConfigParser mConfig
TaskDefinitions & mTasks = const_cast<TaskDefinitions&>(mConfig.tasks())
unordered_multimap< string, Table > mTables
vector< ObjectType > mAvailableCavities
Additional Inherited Members
Public Types inherited from atwork_commander::task_generator::GeneratorPluginInterface
using Task = ::atwork_commander_msgs::Task
Detailed Description
Task Generation Implementation.
Implements the generation of Task according to supplied configurations.
Definition at line 265 of file Generator.cpp.
Member Function Documentation
virtual bool atwork_commander::task_generator::simple::Generator::check (const Task & task) const inline virtual
Todo:
Implement
Implements atwork_commander::task_generator::GeneratorPluginInterface.
Definition at line 773 of file Generator.cpp.
static void atwork_commander::task_generator::simple::Generator::cleanTypes (vector< ObjectType > & types) inline static private
Definition at line 490 of file Generator.cpp.
virtual ConfigParserInterface& atwork_commander::task_generator::simple::Generator::config () inline virtual
Implements atwork_commander::task_generator::GeneratorPluginInterface.
Definition at line 803 of file Generator.cpp.
References PLUGINLIB_EXPORT_CLASS().
static auto atwork_commander::task_generator::simple::Generator::extractCavities (const ArenaDescription & arena) inline static private
Definition at line 267 of file Generator.cpp.
References atwork_commander::ArenaDescription::cavities.
auto atwork_commander::task_generator::simple::Generator::extractObjectTypes (const string & task) inline private
Definition at line 279 of file Generator.cpp.
vector<TablePtr> atwork_commander::task_generator::simple::Generator::extractTablesByTypes (vector< string > types) inline private
Definition at line 334 of file Generator.cpp.
References start().
virtual Task atwork_commander::task_generator::simple::Generator::generate (const std::string & taskName) inline virtual
Implements atwork_commander::task_generator::GeneratorPluginInterface.
Definition at line 785 of file Generator.cpp.
vector<Object*> atwork_commander::task_generator::simple::Generator::generateCavities (TaskDefinition & def, vector< ObjectType > & availableCavities, vector< Object >::iterator start) inline private
Definition at line 495 of file Generator.cpp.
References start().
vector<Object*> atwork_commander::task_generator::simple::Generator::generateContainers (TaskDefinition & def, vector< ObjectType > & availableObjects, vector< Object >::iterator start) inline private
Todo:
Implement generation of all container types on the same table
Definition at line 522 of file Generator.cpp.
References atwork_commander::TaskDefinition::normalTableTypes, atwork_commander::TaskDefinition::parameters, atwork_commander::TaskDefinition::shTypes, atwork_commander::task_generator::Object::source, start(), and atwork_commander::TaskDefinition::ttTypes.
Task atwork_commander::task_generator::simple::Generator::generateImpl (const string & taskName) inline private
Definition at line 629 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::form, and start().
vector<Object*> atwork_commander::task_generator::simple::Generator::generateObjects (TaskDefinition & def, vector< ObjectType * > availableObjects, vector< Object >::iterator start, size_t objectCount, size_t decoyCount) inline private
Definition at line 552 of file Generator.cpp.
References atwork_commander::task_generator::ObjectType::count, error, and start().
vector<Object*> atwork_commander::task_generator::simple::Generator::generateObjects (TaskDefinition & def, vector< ObjectType > availableObjects, vector< Object >::iterator start, size_t objectCount = 1, size_t decoyCount = 0) inline private
Definition at line 574 of file Generator.cpp.
template<typename F > vector<Object*> atwork_commander::task_generator::simple::Generator::generateObjects (TaskDefinition & def, vector< ObjectType > availableObjects, vector< Object >::iterator start, size_t objectCount, size_t decoyCount, F && filter) inline private
Definition at line 581 of file Generator.cpp.
virtual void atwork_commander::task_generator::simple::Generator::onInit (const std::string & arenaConfig, const std::string & taskConfig) inline virtual
Implements atwork_commander::task_generator::GeneratorPluginInterface.
Definition at line 757 of file Generator.cpp.
References atwork_commander::task_generator::DefaultConfigParser::arena(), atwork_commander::ConfigParserInterface::reload(), and atwork_commander::ArenaDescription::workstations.
void atwork_commander::task_generator::simple::Generator::pick (TaskDefinition & def, Object & object, vector< string > tableTypes) inline private
Definition at line 614 of file Generator.cpp.
void atwork_commander::task_generator::simple::Generator::place (TaskDefinition & def, Object & object, vector< string > tableTypes) inline private
Definition at line 591 of file Generator.cpp.
void atwork_commander::task_generator::simple::Generator::place (TaskDefinition & def, Object & object, Object & container) inline private
Definition at line 605 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::orientation, atwork_commander::TaskDefinition::parameters, atwork_commander::task_generator::Object::source, and atwork_commander::task_generator::ObjectBase::type.
void atwork_commander::task_generator::simple::Generator::sanityCheck (std::string task, const vector< ObjectType > & availableObjects) inline private
Definition at line 287 of file Generator.cpp.
void atwork_commander::task_generator::simple::Generator::sanityCheck () inline private
Definition at line 317 of file Generator.cpp.
uint16_t atwork_commander::task_generator::simple::Generator::toCavityType (const Object & o) inline private
Definition at line 364 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::form, and atwork_commander::task_generator::ObjectBase::orientation.
uint16_t atwork_commander::task_generator::simple::Generator::toColoredObjectType (const Object & o) inline private
Definition at line 404 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::color, and atwork_commander::task_generator::ObjectBase::form.
uint16_t atwork_commander::task_generator::simple::Generator::toContainerType (const Object & o) inline private
Definition at line 358 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::color.
uint16_t atwork_commander::task_generator::simple::Generator::toObjectType (const Object & o) inline private
Definition at line 416 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::form.
template<typename T > static vector<T*> atwork_commander::task_generator::simple::Generator::toPtr (typename vector< T >::iterator start, typename vector< T >::iterator end) inline static private
Definition at line 352 of file Generator.cpp.
Task atwork_commander::task_generator::simple::Generator::toTask (const vector< Object > & objects) inline private
Definition at line 448 of file Generator.cpp.
atwork_commander_msgs::Object atwork_commander::task_generator::simple::Generator::toTaskObject (const Object & o) inline private
Definition at line 429 of file Generator.cpp.
References atwork_commander::task_generator::Object::container, and atwork_commander::task_generator::ObjectBase::type.
template<typename T > T& atwork_commander::task_generator::simple::Generator::uniqueSelect (typename vector< T >::iterator start, typename vector< T >::iterator & end) inline private
Definition at line 480 of file Generator.cpp.
Member Data Documentation
vector<ObjectType> atwork_commander::task_generator::simple::Generator::mAvailableCavities private
Definition at line 277 of file Generator.cpp.
DefaultConfigParser atwork_commander::task_generator::simple::Generator::mConfig private
Definition at line 274 of file Generator.cpp.
default_random_engine atwork_commander::task_generator::simple::Generator::mRand private
Definition at line 273 of file Generator.cpp.
unordered_multimap<string, Table> atwork_commander::task_generator::simple::Generator::mTables private
Definition at line 276 of file Generator.cpp.
TaskDefinitions& atwork_commander::task_generator::simple::Generator::mTasks = const_cast<TaskDefinitions&>(mConfig.tasks()) private
Definition at line 275 of file Generator.cpp.
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_gen/src/simple/Generator.cpp