atwork-commander: atwork_commander::com_plugin::Base Class Reference
atwork_commander::com_plugin::Base Class Reference abstract
#include <plugin_interface.h>
Public Member Functions
virtual ~Base ()
void initialize (ros::NodeHandle roshandle, robot_state_fct_t rsf)
Initalize the global variables.
virtual void sendTask (atwork_commander_msgs::Task task)=0
Protected Member Functions
virtual void onInit (ros::NodeHandle roshandle)
In this function the plugIn can do some initialisation depending on a ROS NodeHandle.
void sendRobotState (atwork_commander_msgs::RobotState robot_state)
Private Attributes
robot_state_fct_t robot_state_fct
Callback executed if a new atwork_commander::RobotState was received.
Detailed Description
Definition at line 13 of file plugin_interface.h.
Constructor & Destructor Documentation
virtual atwork_commander::com_plugin::Base::~Base () inline virtual
Definition at line 19 of file plugin_interface.h.
Member Function Documentation
void atwork_commander::com_plugin::Base::initialize (ros::NodeHandle roshandle, robot_state_fct_t rsf) inline
Initalize the global variables.
Parameters
roshandle a valid ROS NodeHandle
rsf callback to handle a newly received atwork_commander_msgs::RobotState
Definition at line 25 of file plugin_interface.h.
References onInit(), and sendTask().
virtual void atwork_commander::com_plugin::Base::onInit (ros::NodeHandle roshandle) inline protected virtual
In this function the plugIn can do some initialisation depending on a ROS NodeHandle.
Parameters
roshandle a valid ROS NodeHandle
Definition at line 38 of file plugin_interface.h.
Referenced by initialize().
void atwork_commander::com_plugin::Base::sendRobotState (atwork_commander_msgs::RobotState robot_state) inline protected
Definition at line 40 of file plugin_interface.h.
References robot_state_fct.
Referenced by atwork_commander::com_plugin::ros::TaskArenaCentric::receiveRobotStateClb().
virtual void atwork_commander::com_plugin::Base::sendTask (atwork_commander_msgs::Task task) pure virtual
Implemented in atwork_commander::com_plugin::ros::TaskObjectCentric, and atwork_commander::com_plugin::ros::TaskArenaCentric.
Referenced by initialize().
Member Data Documentation
robot_state_fct_t atwork_commander::com_plugin::Base::robot_state_fct private
Callback executed if a new atwork_commander::RobotState was received.
Definition at line 15 of file plugin_interface.h.
Referenced by sendRobotState().
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_com/include/atwork_commander_com/plugin_interface.h