atwork-commander: atwork_commander::Control Class Reference
atwork_commander::Control Class Reference
Interface class to the new RefBox of the @Work League.
#include <Control.hpp>
Public Types
using Robots = std::vector< std::string >
Start argument type declaration.
using RefboxState = atwork_commander_msgs::RefboxState
State type of the RefBox.
using StateUpdateCallback = std::function< void(const RefboxState &)>
Callback definition of state callback.
using Task = atwork_commander_msgs::Task
Task type definition.
Public Member Functions
Control (std::string refboxName="atwork_commander")
Constructor connecting to RefBox.
~Control () noexcept
Destructur severing the connection to the RefBox.
void verbose (bool value)
Setter of output / logging verbosity.
bool verbose () const
Getter of verbosity.
void refbox (const std::string &name)
Setter of RefBox namespace.
const std::string & refbox () const
Getter of RefBox namespace.
const RefboxState & state () const
Getter of RefBox state.
void stateUpdateCallback (StateUpdateCallback callback)
Setter of state update callback.
const StateUpdateCallback & stateUpdateCallback () const
Getter of state update callback.
Task generate (const std::string &task)
Command to generate a new Task on the RefBox.
void start (Robots robots={})
Command to start the current Task of the RefBox.
void forward ()
Command to forward the current state of the RefBox manually.
void stop ()
Command to stop the ongoing task of the RefBox.
void store (boost::filesystem::path fileName)
Command to store the current task of the RefBox locally.
void load (boost::filesystem::path fileName)
Command to load a locally stored task in the RefBox.
Private Attributes
ControlImpl * mImpl
pImpl, Pointer to implementation to decouple interface and implementation
Detailed Description
Interface class to the new RefBox of the @Work League.
The interface class allows easy connection to the RefBox updating the RefboxState and supplying control commands to change the state of the RefBox. The commands may throw a ControlError indicating errors in executing them. If no exception is thrown the command is successfull.
Definition at line 75 of file Control.hpp.
Member Typedef Documentation
using atwork_commander::Control::RefboxState = atwork_commander_msgs::RefboxState
State type of the RefBox.
Definition at line 79 of file Control.hpp.
using atwork_commander::Control::Robots = std::vector< std::string >
Start argument type declaration.
Definition at line 78 of file Control.hpp.
using atwork_commander::Control::StateUpdateCallback = std::function<void(const RefboxState&)>
Callback definition of state callback.
Definition at line 80 of file Control.hpp.
using atwork_commander::Control::Task = atwork_commander_msgs::Task
Task type definition.
Definition at line 81 of file Control.hpp.
Constructor & Destructor Documentation
atwork_commander::Control::Control (std::string refboxName = "atwork_commander")
Constructor connecting to RefBox.
Parameters
refboxName the namespace of the RefBox to connect to
Definition at line 212 of file control.cpp.
atwork_commander::Control::~Control () noexcept
Destructur severing the connection to the RefBox.
Definition at line 216 of file control.cpp.
References mImpl.
Member Function Documentation
void atwork_commander::Control::forward ()
Command to forward the current state of the RefBox manually.
State forwarding is only allowed in PREPARATION and EXECUTION phases according to:
Forward Command State Chart
Allowed RefBox states: PREPARATION, EXECUTION
Exceptions
ControlError
Definition at line 221 of file control.cpp.
References atwork_commander::ControlImpl::forward(), and mImpl.
Referenced by forward(), and main().
Task atwork_commander::Control::generate (const std::string & task)
Command to generate a new Task on the RefBox.
The old task will get replaced. Consider calling store to safe the current task. Task will be randomly generated using the configured task generator.
Generate Command State Chart
Allowed RefBox states: IDLE, READY
See also
RefboxState
Exceptions
ControlError
Parameters
task the name of the task type to be generated
Definition at line 219 of file control.cpp.
References atwork_commander::ControlImpl::generate(), and mImpl.
Referenced by generate(), and main().
void atwork_commander::Control::load (boost::filesystem::path fileName)
Command to load a locally stored task in the RefBox.
The locally stored file will be parsed and submitted to the RefBox, if no task is currently executed. If the file does not exist or does not contain a valid task, a PATH_INVALID ControlError will be thrown.
Allowed RefBox states: IDLE, READY
Exceptions
ControlError
Parameters
fileName filesystem path to load task from
Definition at line 224 of file control.cpp.
References atwork_commander::ControlImpl::load(), and mImpl.
Referenced by load().
void atwork_commander::Control::refbox (const std::string & name)
Setter of RefBox namespace.
Parameters
name Namespace of RefBox to connect to
Definition at line 233 of file control.cpp.
References mImpl, and atwork_commander::ControlImpl::refbox.
Referenced by main(), and atwork_commander::testing::BasicControlTest::SetUp().
const std::string & atwork_commander::Control::refbox () const
Getter of RefBox namespace.
Returns
RefBox namespace
Definition at line 230 of file control.cpp.
References mImpl, and atwork_commander::ControlImpl::refbox.
void atwork_commander::Control::start (Robots robots = {})
Command to start the current Task of the RefBox.
A list of robots to start the task on can be supplied. If none is supplied the task will be started on all robots. Supplied robot names need to be in form <team name>/<robot name>.
Start Command State Chart
Allowed RefBox states: READY
See also
RefboxState
Exceptions
ControlError
Parameters
robots List of robot names to start task on.
Definition at line 220 of file control.cpp.
References mImpl, and atwork_commander::ControlImpl::start().
Referenced by main(), and start().
const Control::RefboxState & atwork_commander::Control::state () const
Getter of RefBox state.
Should not be relyed on if accessed from another thread then the global callback queue of ros is executed on. Please use stateUpdateCallback to set a callback, which is executed in the same thread context and enable manual thread synchronization.
Warning
Thread-Safety: Unsafe
Returns
constant reference to RefBox state
Definition at line 228 of file control.cpp.
References mImpl, and atwork_commander::ControlImpl::state.
Referenced by main().
void atwork_commander::Control::stateUpdateCallback (StateUpdateCallback callback)
Setter of state update callback.
State update callback can be a static function or lambda function or member function. In case of member function std::bind is necessary to enable binding, e.g: std::bind(&<MyClass>::<MyFunction>, this, std::placeholders::_1).
Parameters
callback to execute on update of RefboxState
Definition at line 234 of file control.cpp.
References atwork_commander::ControlImpl::callback, and mImpl.
Referenced by main().
const Callback & atwork_commander::Control::stateUpdateCallback () const
Getter of state update callback.
Returns
currently set stateUpdateCallback
Definition at line 229 of file control.cpp.
References atwork_commander::ControlImpl::callback, and mImpl.
void atwork_commander::Control::stop ()
Command to stop the ongoing task of the RefBox.
Stops the ongoing task by transition to READY from PREPARATION or EXECUTION
Stop Command State Chart
Allowed RefBox states: IDLE, READY, PREPARATION, EXECUTION
Exceptions
ControlError
Definition at line 222 of file control.cpp.
References mImpl, and atwork_commander::ControlImpl::stop().
Referenced by stop().
void atwork_commander::Control::store (boost::filesystem::path fileName)
Command to store the current task of the RefBox locally.
If no valid task is currently registered in the RefBox the command will fail with a SERVICE_ERROR. If the supplied path is not existing it will be created. If the supplied path is a directory or non-regular file, the command will fail with PATH_INVALID.
Allowed RefBox states: atwork_commander_msgs::RefboxState_::IDLE, atwork_commander_msgs::RefboxState_::READY, atwork_commander_msgs::RefboxState_::PREPARATION, atwork_commander_msgs::RefboxState_::EXECUTION
Exceptions
ControlError
Parameters
fileName filesystem path to store task to
Definition at line 223 of file control.cpp.
References mImpl, and atwork_commander::ControlImpl::store().
Referenced by store().
void atwork_commander::Control::verbose (bool value)
Setter of output / logging verbosity.
All debug information is published on the DEBUG log level of ROS
Parameters
value If "true" enables additional output within commands to ease debugging
Definition at line 235 of file control.cpp.
References mImpl, and atwork_commander::ControlImpl::verbose.
bool atwork_commander::Control::verbose () const
Getter of verbosity.
Returns
current state of verbosity
Definition at line 227 of file control.cpp.
References mImpl, and atwork_commander::ControlImpl::verbose.
Member Data Documentation
ControlImpl* atwork_commander::Control::mImpl private
pImpl, Pointer to implementation to decouple interface and implementation
Definition at line 76 of file Control.hpp.
Referenced by forward(), generate(), load(), refbox(), start(), state(), stateUpdateCallback(), stop(), store(), verbose(), and ~Control().
The documentation for this class was generated from the following files:
/home/travis/build/steup/atwork-commander/atwork_commander_core/include/atwork_commander/Control.hpp
/home/travis/build/steup/atwork-commander/atwork_commander_core/src/control.cpp