atwork-commander: atwork_commander::task_generator::jurek::Generator Class Reference
atwork_commander::task_generator::jurek::Generator Class Reference
Task Generation Implementation.
Public Member Functions
void checkPickNeqPlace (const run &tasks) const
void checkPickCounts (const run &tasks, Parameters params) const
void checkPlaceCounts (const run &tasks, Parameters params) const
void checkContainers (const run &tasks, Parameters params)
virtual void onInit (const std::string &arenaConfig, const std::string &taskConfig)
virtual bool check (const Task &task) const
virtual Task generate (const std::string &taskName)
virtual ConfigParserInterface & config ()
Public Member Functions inherited from atwork_commander::task_generator::GeneratorPluginInterface
virtual ~GeneratorPluginInterface ()
Private Types
using Parameters = std::map< std::string, int >
using run = vector< array< int, 5 >>
Private Member Functions
auto extractObjectTypes (const string &task)
auto extractObjectTypes (const ArenaDescription &arena)
void sanityCheck ()
uint16_t toContainerType (const ObjectType &o)
uint16_t toCavityType (const ObjectType &o)
uint16_t toColoredObjectType (const ObjectType &o)
uint16_t toObjectType (const ObjectType &o)
atwork_commander_msgs::Object toTaskObject (const ObjectType &o)
atwork_commander_msgs::Object toTaskObject (const Object &o)
size_t toCavity (size_t id, Orientation o) const
Task toTask (const vector< array< int, 5 >> &run) const
string printError (int error) const
void readParameters (const string &taskName)
vector< array< int, 5 > > fromTask (const Task &origTask)
void debugAll (const string info, const run &tasks)
void debug_tasks (const string info, const run &tasks) const
void generate_objects (run &tasks)
void checkObjectTypes (const Task &task) const
std::vector< size_t > order (size_t n)
void variation (vector< size_t > position, size_t k, vector< size_t > &vec_k, vector< size_t > &vec_n_k)
void variation (vector< size_t > &positions, size_t k, vector< size_t > &vec_k)
size_t get_container_id (const size_t table, const size_t color)
void initialize_mAllTables ()
void initialize_validpicks (run &tasks)
void initialize_picksleft ()
void initialize_mTableTypes ()
size_t sum_vector (vector< size_t > &vec)
size_t shortest_list (size_t &min)
void update_validpicks (size_t type_id)
Task generateImpl (const string &taskName)
Static Private Member Functions
static auto extractCavities (const ArenaDescription &arena)
Private Attributes
default_random_engine mRand
DefaultConfigParser mConfig
TaskDefinitions & mTasks = const_cast<TaskDefinitions&>(mConfig.tasks())
unordered_multimap< string, Table > mTables
vector< ObjectType > mAvailableCavities
vector< ObjectType > mAvailableObjects
vector< std::array< size_t, 3 > > container_ids
vector< string > mTablesInverse
unsigned int contId = 1
std::vector< std::string > mTableMapping
std::vector< unsigned int > mJTables
std::vector< unsigned int > mTables0
std::vector< unsigned int > mTables5
std::vector< unsigned int > mTables10
std::vector< unsigned int > mTables15
std::vector< unsigned int > mConveyors
std::vector< unsigned int > mPpts
std::vector< unsigned int > mShelfs
std::vector< unsigned int > mWaypoints
std::vector< unsigned int > mObjects
std::vector< unsigned int > mPptObjects
std::vector< size_t > mAllTables
int mdiscipline
Parameters paramBNT
Parameters paramBTT3
Parameters paramFinal
int estimatet_active
bool paramContainerInShelf
bool paramContainerOnPpt
bool paramContainerOnTurntable
bool paramFlexibleHeight
std::vector< std::vector< size_t > > validpicks
std::vector< size_t > picksleft
std::unordered_map< size_t, size_t > mTableTypes
vector< set< ObjectType > > mAvailableObjectsPerTable
size_t tabletypes
Static Private Attributes
static const size_t obj_id = 0
static const size_t src_id = 1
static const size_t dst_id = 2
static const size_t cont_id = 3
static const size_t obj_id_id = 4
static const size_t blue = atwork_commander_msgs::Object::CONTAINER_BLUE
static const size_t red = atwork_commander_msgs::Object::CONTAINER_RED
static const size_t tables0_id = 0
static const size_t tables5_id = 1
static const size_t tables10_id = 2
static const size_t tables15_id = 3
static const size_t conveyors_id = 4
static const size_t ppts_id = 5
static const size_t shelfs_id = 6
Additional Inherited Members
Public Types inherited from atwork_commander::task_generator::GeneratorPluginInterface
using Task = ::atwork_commander_msgs::Task
Detailed Description
Task Generation Implementation.
Implements the generation of Task according to supplied configurations.
Definition at line 24 of file Generator.cpp.
Member Typedef Documentation
using atwork_commander::task_generator::jurek::Generator::Parameters = std::map<std::string, int> private
Definition at line 290 of file Generator.cpp.
using atwork_commander::task_generator::jurek::Generator::run = vector<array<int, 5>> private
Definition at line 305 of file Generator.cpp.
Member Function Documentation
virtual bool atwork_commander::task_generator::jurek::Generator::check (const Task & task) const inline virtual
Implements atwork_commander::task_generator::GeneratorPluginInterface.
Definition at line 1129 of file Generator.cpp.
References checkContainers(), checkObjectTypes(), checkPickCounts(), checkPickNeqPlace(), checkPlaceCounts(), debug_tasks(), error, and fromTask().
void atwork_commander::task_generator::jurek::Generator::checkContainers (const run & tasks, Parameters params) inline
Definition at line 1069 of file Generator.cpp.
References blue.
Referenced by check(), and generateImpl().
void atwork_commander::task_generator::jurek::Generator::checkObjectTypes (const Task & task) const inline private
Definition at line 535 of file Generator.cpp.
References atwork_commander::task_generator::FREE, atwork_commander::task_generator::HORIZONTAL, toCavity(), and atwork_commander::task_generator::VERTICAL.
Referenced by check().
void atwork_commander::task_generator::jurek::Generator::checkPickCounts (const run & tasks, Parameters params) const inline
Definition at line 981 of file Generator.cpp.
Referenced by check(), and generateImpl().
void atwork_commander::task_generator::jurek::Generator::checkPickNeqPlace (const run & tasks) const inline
Definition at line 970 of file Generator.cpp.
Referenced by check(), and generateImpl().
void atwork_commander::task_generator::jurek::Generator::checkPlaceCounts (const run & tasks, Parameters params) const inline
Definition at line 1026 of file Generator.cpp.
Referenced by check(), and generateImpl().
virtual ConfigParserInterface& atwork_commander::task_generator::jurek::Generator::config () inline virtual
Implements atwork_commander::task_generator::GeneratorPluginInterface.
Definition at line 1172 of file Generator.cpp.
References mConfig, and PLUGINLIB_EXPORT_CLASS().
void atwork_commander::task_generator::jurek::Generator::debug_tasks (const string info, const run & tasks) const inline private
Definition at line 472 of file Generator.cpp.
Referenced by check().
void atwork_commander::task_generator::jurek::Generator::debugAll (const string info, const run & tasks) inline private
Definition at line 462 of file Generator.cpp.
References container_ids, mAllTables, picksleft, and validpicks.
Referenced by generateImpl().
static auto atwork_commander::task_generator::jurek::Generator::extractCavities (const ArenaDescription & arena) inline static private
Definition at line 26 of file Generator.cpp.
References atwork_commander::ArenaDescription::cavities.
Referenced by onInit().
auto atwork_commander::task_generator::jurek::Generator::extractObjectTypes (const string & task) inline private
Definition at line 42 of file Generator.cpp.
Referenced by onInit().
auto atwork_commander::task_generator::jurek::Generator::extractObjectTypes (const ArenaDescription & arena) inline private
Definition at line 50 of file Generator.cpp.
References atwork_commander::ArenaDescription::objects.
vector<array<int, 5> > atwork_commander::task_generator::jurek::Generator::fromTask (const Task & origTask) inline private
Definition at line 415 of file Generator.cpp.
References atwork_commander::task_generator::jurek::Converter::diff(), atwork_commander::task_generator::jurek::Converter::findContainer(), atwork_commander::task_generator::jurek::Converter::findObject(), atwork_commander::task_generator::jurek::Converter::intersect(), readParameters(), start(), and atwork_commander::task_generator::jurek::Converter::toMap().
Referenced by check().
virtual Task atwork_commander::task_generator::jurek::Generator::generate (const std::string & taskName) inline virtual
Implements atwork_commander::task_generator::GeneratorPluginInterface.
Definition at line 1151 of file Generator.cpp.
References generateImpl().
void atwork_commander::task_generator::jurek::Generator::generate_objects (run & tasks) inline private
Definition at line 487 of file Generator.cpp.
References toTaskObject().
Referenced by generateImpl().
Task atwork_commander::task_generator::jurek::Generator::generateImpl (const string & taskName) inline private
Definition at line 752 of file Generator.cpp.
References checkContainers(), checkPickCounts(), checkPickNeqPlace(), checkPlaceCounts(), debugAll(), atwork_commander::task_generator::FREE, generate_objects(), get_container_id(), initialize_mAllTables(), initialize_mTableTypes(), initialize_picksleft(), initialize_validpicks(), mJTables, order(), printError(), readParameters(), shortest_list(), sum_vector(), toCavity(), toObjectType(), toTask(), update_validpicks(), and variation().
Referenced by generate().
size_t atwork_commander::task_generator::jurek::Generator::get_container_id (const size_t table, const size_t color) inline private
Definition at line 630 of file Generator.cpp.
References blue, and red.
Referenced by generateImpl().
void atwork_commander::task_generator::jurek::Generator::initialize_mAllTables () inline private
Definition at line 651 of file Generator.cpp.
Referenced by generateImpl().
void atwork_commander::task_generator::jurek::Generator::initialize_mTableTypes () inline private
Definition at line 694 of file Generator.cpp.
References conveyors_id, ppts_id, shelfs_id, tables0_id, tables10_id, tables15_id, and tables5_id.
Referenced by generateImpl().
void atwork_commander::task_generator::jurek::Generator::initialize_picksleft () inline private
Definition at line 682 of file Generator.cpp.
Referenced by generateImpl().
void atwork_commander::task_generator::jurek::Generator::initialize_validpicks (run & tasks) inline private
Definition at line 666 of file Generator.cpp.
Referenced by generateImpl().
virtual void atwork_commander::task_generator::jurek::Generator::onInit (const std::string & arenaConfig, const std::string & taskConfig) inline virtual
Implements atwork_commander::task_generator::GeneratorPluginInterface.
Definition at line 1112 of file Generator.cpp.
References atwork_commander::task_generator::DefaultConfigParser::arena(), extractCavities(), extractObjectTypes(), atwork_commander::ConfigParserInterface::reload(), sanityCheck(), and atwork_commander::ArenaDescription::workstations.
std::vector<size_t> atwork_commander::task_generator::jurek::Generator::order (size_t n) inline private
Definition at line 599 of file Generator.cpp.
Referenced by generateImpl().
string atwork_commander::task_generator::jurek::Generator::printError (int error) const inline private
Definition at line 228 of file Generator.cpp.
Referenced by generateImpl().
void atwork_commander::task_generator::jurek::Generator::readParameters (const string & taskName) inline private
Definition at line 307 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::form, atwork_commander::task_generator::Table::name, atwork_commander::TaskDefinition::objects, toTaskObject(), and atwork_commander::task_generator::Table::type.
Referenced by fromTask(), and generateImpl().
void atwork_commander::task_generator::jurek::Generator::sanityCheck () inline private
Definition at line 58 of file Generator.cpp.
Referenced by onInit().
size_t atwork_commander::task_generator::jurek::Generator::shortest_list (size_t & min) inline private
Definition at line 728 of file Generator.cpp.
Referenced by generateImpl().
size_t atwork_commander::task_generator::jurek::Generator::sum_vector (vector< size_t > & vec) inline private
Definition at line 719 of file Generator.cpp.
Referenced by generateImpl().
size_t atwork_commander::task_generator::jurek::Generator::toCavity (size_t id, Orientation o) const inline private
Definition at line 169 of file Generator.cpp.
Referenced by checkObjectTypes(), generateImpl(), and toTask().
uint16_t atwork_commander::task_generator::jurek::Generator::toCavityType (const ObjectType & o) inline private
Definition at line 81 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::form, atwork_commander::task_generator::FREE, atwork_commander::task_generator::HORIZONTAL, atwork_commander::task_generator::ObjectBase::orientation, and atwork_commander::task_generator::VERTICAL.
Referenced by toTaskObject().
uint16_t atwork_commander::task_generator::jurek::Generator::toColoredObjectType (const ObjectType & o) inline private
Definition at line 121 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::color, and atwork_commander::task_generator::ObjectBase::form.
Referenced by toTaskObject().
uint16_t atwork_commander::task_generator::jurek::Generator::toContainerType (const ObjectType & o) inline private
Definition at line 75 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::color.
Referenced by toTaskObject().
uint16_t atwork_commander::task_generator::jurek::Generator::toObjectType (const ObjectType & o) inline private
Definition at line 133 of file Generator.cpp.
References atwork_commander::task_generator::ObjectBase::form.
Referenced by generateImpl(), and toTaskObject().
Task atwork_commander::task_generator::jurek::Generator::toTask (const vector< array< int, 5 >> & run) const inline private
Definition at line 185 of file Generator.cpp.
References cont_id, dst_id, atwork_commander::task_generator::FREE, obj_id, src_id, and toCavity().
Referenced by generateImpl().
atwork_commander_msgs::Object atwork_commander::task_generator::jurek::Generator::toTaskObject (const ObjectType & o) inline private
Definition at line 146 of file Generator.cpp.
References atwork_commander::task_generator::CAVITY, atwork_commander::task_generator::COLORED_OBJECT, atwork_commander::task_generator::CONTAINER, atwork_commander::task_generator::OBJECT, toCavityType(), toColoredObjectType(), toContainerType(), toObjectType(), and atwork_commander::task_generator::ObjectBase::type.
Referenced by generate_objects(), readParameters(), and toTaskObject().
atwork_commander_msgs::Object atwork_commander::task_generator::jurek::Generator::toTaskObject (const Object & o) inline private
Definition at line 157 of file Generator.cpp.
References atwork_commander::task_generator::CAVITY, atwork_commander::task_generator::CONTAINER, toCavityType(), toContainerType(), toTaskObject(), and atwork_commander::task_generator::ObjectBase::type.
void atwork_commander::task_generator::jurek::Generator::update_validpicks (size_t type_id) inline private
Definition at line 741 of file Generator.cpp.
Referenced by generateImpl().
void atwork_commander::task_generator::jurek::Generator::variation (vector< size_t > position, size_t k, vector< size_t > & vec_k, vector< size_t > & vec_n_k) inline private
Definition at line 610 of file Generator.cpp.
Referenced by generateImpl(), and variation().
void atwork_commander::task_generator::jurek::Generator::variation (vector< size_t > & positions, size_t k, vector< size_t > & vec_k) inline private
Definition at line 625 of file Generator.cpp.
References variation().
Member Data Documentation
const size_t atwork_commander::task_generator::jurek::Generator::blue = atwork_commander_msgs::Object::CONTAINER_BLUE static private
Definition at line 280 of file Generator.cpp.
Referenced by checkContainers(), and get_container_id().
const size_t atwork_commander::task_generator::jurek::Generator::cont_id = 3 static private
Definition at line 277 of file Generator.cpp.
Referenced by toTask().
vector<std::array<size_t, 3> > atwork_commander::task_generator::jurek::Generator::container_ids private
Definition at line 39 of file Generator.cpp.
Referenced by debugAll().
unsigned int atwork_commander::task_generator::jurek::Generator::contId = 1 private
Definition at line 222 of file Generator.cpp.
const size_t atwork_commander::task_generator::jurek::Generator::conveyors_id = 4 static private
Definition at line 287 of file Generator.cpp.
Referenced by initialize_mTableTypes().
const size_t atwork_commander::task_generator::jurek::Generator::dst_id = 2 static private
Definition at line 276 of file Generator.cpp.
Referenced by toTask().
int atwork_commander::task_generator::jurek::Generator::estimatet_active private
Definition at line 294 of file Generator.cpp.
std::vector<size_t> atwork_commander::task_generator::jurek::Generator::mAllTables private
Definition at line 271 of file Generator.cpp.
Referenced by debugAll().
vector<ObjectType> atwork_commander::task_generator::jurek::Generator::mAvailableCavities private
Definition at line 37 of file Generator.cpp.
vector<ObjectType> atwork_commander::task_generator::jurek::Generator::mAvailableObjects private
Definition at line 38 of file Generator.cpp.
vector<set<ObjectType> > atwork_commander::task_generator::jurek::Generator::mAvailableObjectsPerTable private
Definition at line 302 of file Generator.cpp.
DefaultConfigParser atwork_commander::task_generator::jurek::Generator::mConfig private
Definition at line 34 of file Generator.cpp.
Referenced by config().
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mConveyors private
Definition at line 265 of file Generator.cpp.
int atwork_commander::task_generator::jurek::Generator::mdiscipline private
Definition at line 273 of file Generator.cpp.
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mJTables private
Definition at line 260 of file Generator.cpp.
Referenced by generateImpl().
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mObjects private
Definition at line 269 of file Generator.cpp.
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mPptObjects private
Definition at line 270 of file Generator.cpp.
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mPpts private
Definition at line 266 of file Generator.cpp.
default_random_engine atwork_commander::task_generator::jurek::Generator::mRand private
Definition at line 33 of file Generator.cpp.
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mShelfs private
Definition at line 267 of file Generator.cpp.
std::vector<std::string> atwork_commander::task_generator::jurek::Generator::mTableMapping private
Definition at line 259 of file Generator.cpp.
unordered_multimap<string, Table> atwork_commander::task_generator::jurek::Generator::mTables private
Definition at line 36 of file Generator.cpp.
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mTables0 private
Definition at line 261 of file Generator.cpp.
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mTables10 private
Definition at line 263 of file Generator.cpp.
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mTables15 private
Definition at line 264 of file Generator.cpp.
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mTables5 private
Definition at line 262 of file Generator.cpp.
vector<string> atwork_commander::task_generator::jurek::Generator::mTablesInverse private
Definition at line 40 of file Generator.cpp.
std::unordered_map<size_t, size_t> atwork_commander::task_generator::jurek::Generator::mTableTypes private
Definition at line 301 of file Generator.cpp.
TaskDefinitions& atwork_commander::task_generator::jurek::Generator::mTasks = const_cast<TaskDefinitions&>(mConfig.tasks()) private
Definition at line 35 of file Generator.cpp.
std::vector<unsigned int> atwork_commander::task_generator::jurek::Generator::mWaypoints private
Definition at line 268 of file Generator.cpp.
const size_t atwork_commander::task_generator::jurek::Generator::obj_id = 0 static private
Definition at line 274 of file Generator.cpp.
Referenced by toTask().
const size_t atwork_commander::task_generator::jurek::Generator::obj_id_id = 4 static private
Definition at line 278 of file Generator.cpp.
Parameters atwork_commander::task_generator::jurek::Generator::paramBNT private
Definition at line 291 of file Generator.cpp.
Parameters atwork_commander::task_generator::jurek::Generator::paramBTT3 private
Definition at line 292 of file Generator.cpp.
bool atwork_commander::task_generator::jurek::Generator::paramContainerInShelf private
Definition at line 295 of file Generator.cpp.
bool atwork_commander::task_generator::jurek::Generator::paramContainerOnPpt private
Definition at line 296 of file Generator.cpp.
bool atwork_commander::task_generator::jurek::Generator::paramContainerOnTurntable private
Definition at line 297 of file Generator.cpp.
Parameters atwork_commander::task_generator::jurek::Generator::paramFinal private
Definition at line 293 of file Generator.cpp.
bool atwork_commander::task_generator::jurek::Generator::paramFlexibleHeight private
Definition at line 298 of file Generator.cpp.
std::vector<size_t> atwork_commander::task_generator::jurek::Generator::picksleft private
Definition at line 300 of file Generator.cpp.
Referenced by debugAll().
const size_t atwork_commander::task_generator::jurek::Generator::ppts_id = 5 static private
Definition at line 288 of file Generator.cpp.
Referenced by initialize_mTableTypes().
const size_t atwork_commander::task_generator::jurek::Generator::red = atwork_commander_msgs::Object::CONTAINER_RED static private
Definition at line 281 of file Generator.cpp.
Referenced by get_container_id().
const size_t atwork_commander::task_generator::jurek::Generator::shelfs_id = 6 static private
Definition at line 289 of file Generator.cpp.
Referenced by initialize_mTableTypes().
const size_t atwork_commander::task_generator::jurek::Generator::src_id = 1 static private
Definition at line 275 of file Generator.cpp.
Referenced by toTask().
const size_t atwork_commander::task_generator::jurek::Generator::tables0_id = 0 static private
Definition at line 283 of file Generator.cpp.
Referenced by initialize_mTableTypes().
const size_t atwork_commander::task_generator::jurek::Generator::tables10_id = 2 static private
Definition at line 285 of file Generator.cpp.
Referenced by initialize_mTableTypes().
const size_t atwork_commander::task_generator::jurek::Generator::tables15_id = 3 static private
Definition at line 286 of file Generator.cpp.
Referenced by initialize_mTableTypes().
const size_t atwork_commander::task_generator::jurek::Generator::tables5_id = 1 static private
Definition at line 284 of file Generator.cpp.
Referenced by initialize_mTableTypes().
size_t atwork_commander::task_generator::jurek::Generator::tabletypes private
Definition at line 304 of file Generator.cpp.
std::vector<std::vector<size_t> > atwork_commander::task_generator::jurek::Generator::validpicks private
Definition at line 299 of file Generator.cpp.
Referenced by debugAll().
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_gen/src/jurek/Generator.cpp