atwork-commander: atwork_commander::MainVisGroup Class Reference
atwork_commander::MainVisGroup Class Reference
The outer Widget managing all subGroups.
#include <rviz_plugin.h>
Public Slots
virtual void callUpdate (int index=-1)
Update via the Refresh Button.
Public Slots inherited from atwork_commander::VisGroup
Public Member Functions
MainVisGroup (QWidget *parent=nullptr)
virtual ~MainVisGroup ()
virtual void setControlPtr (std::shared_ptr< atwork_commander::Control > new_control_ptr)
virtual void update () override
Reimplementation of the Qt function.
void registerSubclass (VisGroup *subGroup, const char *display_name)
Hand a VisGroup-SubClass-Instance over to the MainVisGroup.
virtual bool hasFocus () override
Disable update of the Widget if hasFocus returns true.
Public Member Functions inherited from atwork_commander::VisGroup
VisGroup (QWidget *parent=nullptr)
virtual ~VisGroup ()
virtual QWidget * getWidget ()
virtual QLayout * getLayout ()
Private Attributes
QComboBox * mainComboBox = nullptr
QStackedWidget * mainStackedWidget = nullptr
QPushButton * refreshButton = nullptr
QHBoxLayout * buttonHBoxLayout = nullptr
QLabel * statusLabel = nullptr
std::vector< VisGroup * > subGroups
Additional Inherited Members
Protected Attributes inherited from atwork_commander::VisGroup
QWidget * self = nullptr
QFormLayout * layout = nullptr
QMessageBox * message = nullptr
std::shared_ptr< atwork_commander::Control > control_ptr
Detailed Description
The outer Widget managing all subGroups.
The MainVisGroup has a couple of tasks
Save the subGroups it gets registered via the registerSubclass-Method
Provide a ComboBox to select the subGroups
Provide a 'Refresh' Button to update the currently selected subGroups
Update subGroups based on WM - Entry-Modified-Callback
Update subGroups periodically based on Timer
Definition at line 116 of file rviz_plugin.h.
Constructor & Destructor Documentation
atwork_commander::MainVisGroup::MainVisGroup (QWidget * parent = nullptr) inline
Definition at line 130 of file rviz_plugin.h.
References atwork_commander::VisGroup::layout.
virtual atwork_commander::MainVisGroup::~MainVisGroup () inline virtual
Definition at line 169 of file rviz_plugin.h.
Member Function Documentation
virtual void atwork_commander::MainVisGroup::callUpdate (int index = -1) inline virtual slot
Update via the Refresh Button.
Definition at line 247 of file rviz_plugin.h.
virtual bool atwork_commander::MainVisGroup::hasFocus () inline override virtual
Disable update of the Widget if hasFocus returns true.
Any subGroup can disable being updated by returning true.
Implements atwork_commander::VisGroup.
Definition at line 233 of file rviz_plugin.h.
void atwork_commander::MainVisGroup::registerSubclass (VisGroup * subGroup, const char * display_name) inline
Hand a VisGroup-SubClass-Instance over to the MainVisGroup.
This makes the SubClass appear in the RViz Plugin. It also causes the SubClass to be managed by the MainVisGroup.
Definition at line 216 of file rviz_plugin.h.
References atwork_commander::VisGroup::getWidget().
Referenced by atwork_commander::RefboxUI::RefboxUI().
virtual void atwork_commander::MainVisGroup::setControlPtr (std::shared_ptr< atwork_commander::Control > new_control_ptr) inline virtual
Reimplemented from atwork_commander::VisGroup.
Definition at line 188 of file rviz_plugin.h.
References atwork_commander::VisGroup::control_ptr.
Referenced by atwork_commander::RefboxUI::RefboxUI().
virtual void atwork_commander::MainVisGroup::update () inline override virtual
Reimplementation of the Qt function.
Updates the UI, usually by getting new data from the Worldmodel and redrawing the thing.
Implements atwork_commander::VisGroup.
Definition at line 206 of file rviz_plugin.h.
Member Data Documentation
QHBoxLayout* atwork_commander::MainVisGroup::buttonHBoxLayout = nullptr private
Definition at line 122 of file rviz_plugin.h.
QComboBox* atwork_commander::MainVisGroup::mainComboBox = nullptr private
Definition at line 119 of file rviz_plugin.h.
QStackedWidget* atwork_commander::MainVisGroup::mainStackedWidget = nullptr private
Definition at line 120 of file rviz_plugin.h.
QPushButton* atwork_commander::MainVisGroup::refreshButton = nullptr private
Definition at line 121 of file rviz_plugin.h.
QLabel* atwork_commander::MainVisGroup::statusLabel = nullptr private
Definition at line 123 of file rviz_plugin.h.
std::vector<VisGroup*> atwork_commander::MainVisGroup::subGroups private
Definition at line 127 of file rviz_plugin.h.
The documentation for this class was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_gui/src/rviz_plugin.h