atwork-commander: atwork_commander::ControlError Class Reference
atwork_commander::ControlError Class Reference
Exceptions thrown by the Control interface of the refbox.
#include <Control.hpp>
Public Types
enum Reasons {
Reasons::PATH_INVALID, Reasons::TASK_INVALID, Reasons::STATE_INVALID, Reasons::ARGUMENT_INVALID,
Reasons::NO_TASK, Reasons::NO_ROBOT, Reasons::SERVICE_ERROR, Reasons::CONNECTION_ERROR
}
Pre-defined error types.
Public Member Functions
ControlError (std::string command, Reasons reason, std::string argument="")
Constructor taking the error description.
Reasons reason () const
Getter for type of error.
const std::string & argument () const
Getter of argument.
const std::string & command () const
Getter of command.
Private Attributes
Reasons mReason
Type of error, see Reasons.
std::string mArgument
Supplied argument of command.
std::string mCommand
Command that failed.
Detailed Description
Exceptions thrown by the Control interface of the refbox.
Each exception has a Reason and an optional argument. The exceptions represents errors created through wrong states, internal errors or wrong arguments passed. The class inherites from std::runtime_error, which allows for automatic printing of error messages in applications not catching the errors.
Definition at line 21 of file Control.hpp.
Member Enumeration Documentation
enum atwork_commander::ControlError::Reasons strong
Pre-defined error types.
Enumerator
PATH_INVALID
Filesystem path is invalid.
TASK_INVALID
Refbox does not contin a valid task.
STATE_INVALID
State of refbox does not fit command.
ARGUMENT_INVALID
Supplied argument is invalid for command.
NO_TASK
Task with the specified name does not exist.
NO_ROBOT
Refbox ha no robots registered.
SERVICE_ERROR
Internal error of the refbox.
CONNECTION_ERROR
Connection to the refbox service could not be established.
Definition at line 25 of file Control.hpp.
Constructor & Destructor Documentation
atwork_commander::ControlError::ControlError (std::string command, ControlError::Reasons reason, std::string argument = "")
Constructor taking the error description.
Parameters
command Command that created the error
reason Type of error
argument Optional argument describing the error
Definition at line 75 of file control.cpp.
Referenced by atwork_commander::ControlImpl::forward(), atwork_commander::ControlImpl::load(), atwork_commander::ControlImpl::start(), atwork_commander::ControlImpl::stop(), and atwork_commander::ControlImpl::store().
Member Function Documentation
const std::string& atwork_commander::ControlError::argument () const inline
Getter of argument.
Returns
optional argument of error, "" is unset
Definition at line 60 of file Control.hpp.
References mArgument.
const std::string& atwork_commander::ControlError::command () const inline
Getter of command.
Returns
command, which created the error
Definition at line 66 of file Control.hpp.
References mCommand.
Reasons atwork_commander::ControlError::reason () const inline
Getter for type of error.
Returns
Type of error
Definition at line 54 of file Control.hpp.
References mReason.
Referenced by atwork_commander::testing::BasicControlTest::expectReason().
Member Data Documentation
std::string atwork_commander::ControlError::mArgument private
Supplied argument of command.
Definition at line 38 of file Control.hpp.
Referenced by argument().
std::string atwork_commander::ControlError::mCommand private
Command that failed.
Definition at line 39 of file Control.hpp.
Referenced by command().
Reasons atwork_commander::ControlError::mReason private
Type of error, see Reasons.
Definition at line 37 of file Control.hpp.
Referenced by reason().
The documentation for this class was generated from the following files:
/home/travis/build/steup/atwork-commander/atwork_commander_core/include/atwork_commander/Control.hpp
/home/travis/build/steup/atwork-commander/atwork_commander_core/src/control.cpp