atwork-commander: /home/travis/build/steup/atwork-commander/atwork_commander_com/src/communication_node.cpp File Reference
communication_node.cpp File Reference
#include "atwork_commander_com/plugin_interface.h"
#include <pluginlib/class_loader.h>
#include <iosfwd>
Typedefs
using if_t = atwork_commander::com_plugin::Base
Functions
void sendTaskClb (const atwork_commander_msgs::Task::ConstPtr &msg)
void receiveRobotState (atwork_commander_msgs::RobotState robot_state)
static ostream & operator<< (ostream &os, const vector< string > &v)
int main (int argc, char **argv)
Variables
ros::Publisher g_robot_state_pub
std::vector< boost::shared_ptr< if_t > > g_plugins
Typedef Documentation
using if_t = atwork_commander::com_plugin::Base
Definition at line 8 of file communication_node.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 33 of file communication_node.cpp.
References g_robot_state_pub, receiveRobotState(), and sendTaskClb().
static ostream& operator<< (ostream & os, const vector< string > & v) static
Definition at line 26 of file communication_node.cpp.
void receiveRobotState (atwork_commander_msgs::RobotState robot_state)
Definition at line 20 of file communication_node.cpp.
References g_robot_state_pub.
Referenced by main().
void sendTaskClb (const atwork_commander_msgs::Task::ConstPtr & msg)
Definition at line 13 of file communication_node.cpp.
Referenced by main().
Variable Documentation
std::vector<boost::shared_ptr<if_t> > g_plugins
Definition at line 11 of file communication_node.cpp.
ros::Publisher g_robot_state_pub
Definition at line 10 of file communication_node.cpp.
Referenced by main(), and receiveRobotState().