atwork-commander: /home/travis/build/steup/atwork-commander/atwork_commander_core/src/control_node.cpp File Reference
control_node.cpp File Reference
#include <atwork_commander/Control.hpp>
#include <ros/ros.h>
#include <boost/program_options.hpp>
#include <string>
#include <vector>
#include <regex>
#include <fstream>
#include <chrono>
#include <thread>
#include <memory>
Enumerations
enum Command {
Command::NOTHING, Command::FORWARD, Command::STOP, Command::START,
Command::GENERATE, Command::STATE, Command::STORE, Command::LOAD
}
Functions
static ostream & operator<< (ostream &os, const vector< string > &v)
static ostream & operator<< (ostream &os, Command cmd)
static bool forward ()
static bool generate ()
static bool stop ()
static bool start ()
static void store ()
static void load ()
static void stateUpdate (const Control::RefboxState &state)
static bool parseArgs (int argc, char **argv)
int main (int argc, char **argv)
Variables
enum Command command
unique_ptr< Control > gControlPtr
string refboxName = "atwork_commander"
vector< string > arguments
bool verbose = false
bool continous = false
int result = 0
Enumeration Type Documentation
enum Command strong
Enumerator
NOTHING
FORWARD
STOP
START
GENERATE
STATE
STORE
LOAD
Definition at line 22 of file control_node.cpp.
Function Documentation
static bool forward () static
Definition at line 61 of file control_node.cpp.
References atwork_commander::Control::forward().
Referenced by stateUpdate().
static bool generate () static
Definition at line 72 of file control_node.cpp.
References atwork_commander::Control::generate().
Referenced by RefboxMockBase::generateCall(), and stateUpdate().
static void load () static
Definition at line 121 of file control_node.cpp.
References atwork_commander::Control::load(), and result.
Referenced by stateUpdate().
int main (int argc, char ** argv)
Definition at line 192 of file control_node.cpp.
References command, NOTHING, parseArgs(), atwork_commander::Control::refbox(), refboxName, result, stateUpdate(), atwork_commander::Control::stateUpdateCallback(), and verbose.
static ostream& operator<< (ostream & os, const vector< string > & v) static
Definition at line 40 of file control_node.cpp.
static ostream& operator<< (ostream & os, Command cmd) static
Definition at line 47 of file control_node.cpp.
References FORWARD, GENERATE, LOAD, NOTHING, START, STATE, STOP, and STORE.
static bool parseArgs (int argc, char ** argv) static
Definition at line 158 of file control_node.cpp.
References arguments, command, continous, FORWARD, GENERATE, LOAD, NOTHING, START, STATE, STOP, STORE, store(), and verbose.
Referenced by main().
static bool start () static
Definition at line 96 of file control_node.cpp.
References atwork_commander::Control::start().
Referenced by atwork_commander::task_generator::simple::Generator::extractTablesByTypes(), atwork_commander::task_generator::jurek::Generator::fromTask(), atwork_commander::task_generator::simple::Generator::generateCavities(), atwork_commander::task_generator::simple::Generator::generateContainers(), atwork_commander::task_generator::simple::Generator::generateImpl(), atwork_commander::task_generator::simple::Generator::generateObjects(), atwork_commander::com_plugin::ros::TaskObjectCentric::sendTask(), RefboxMockBase::startCall(), stateUpdate(), and TEST_F().
static void stateUpdate (const Control::RefboxState & state) static
Definition at line 136 of file control_node.cpp.
References command, continous, FORWARD, forward(), GENERATE, generate(), LOAD, load(), result, START, start(), STOP, stop(), STORE, store(), and verbose.
Referenced by main().
static bool stop () static
Definition at line 86 of file control_node.cpp.
References atwork_commander::Control::stop().
Referenced by stateUpdate().
static void store () static
Definition at line 106 of file control_node.cpp.
References result, and atwork_commander::Control::store().
Referenced by parseArgs(), and stateUpdate().
Variable Documentation
vector<string> arguments
Definition at line 35 of file control_node.cpp.
Referenced by parseArgs().
enum Command command
Referenced by main(), parseArgs(), and stateUpdate().
bool continous = false
Definition at line 37 of file control_node.cpp.
Referenced by parseArgs(), and stateUpdate().
unique_ptr<Control> gControlPtr
Definition at line 33 of file control_node.cpp.
string refboxName = "atwork_commander"
Definition at line 34 of file control_node.cpp.
Referenced by main(), and atwork_commander::RefboxUI::RefboxUI().
int result = 0
Definition at line 38 of file control_node.cpp.
Referenced by atwork_commander::task_generator::jurek::Converter::diff(), atwork_commander::com_plugin::ros::TaskObjectCentric::diff(), atwork_commander::task_generator::jurek::Converter::intersect(), atwork_commander::com_plugin::ros::TaskObjectCentric::intersect(), load(), main(), atwork_commander::task_generator::readStruct(), stateUpdate(), store(), atwork_commander::task_generator::jurek::Converter::toMap(), and atwork_commander::com_plugin::ros::TaskObjectCentric::toMap().
bool verbose = false
Definition at line 36 of file control_node.cpp.
Referenced by main(), parseArgs(), and stateUpdate().