atwork-commander: /home/travis/build/steup/atwork-commander/atwork_commander_gen/src/Error.h File Reference
Error.h File Reference
#include <stdexcept>
#include <iostream>
#include <sstream>
Macros
#define error(msg, ...) errorImpl(__FILE__, __LINE__, __PRETTY_FUNCTION__, msg, __VA_ARGS__);
Functions
void errorOut (std::ostream &os, const char *v)
template<typename T >
void errorOut (std::ostream &os, T v)
template<typename T >
void errorPass (std::ostream &os, T first)
template<typename T , typename... Args>
void errorPass (std::ostream &os, T first, Args...args)
template<typename... Args>
void errorImpl (const char *file, size_t line, const char *func, const char *msg, Args...args)
Macro Definition Documentation
#define error (msg, ...) errorImpl(__FILE__, __LINE__, __PRETTY_FUNCTION__, msg, __VA_ARGS__);
Definition at line 33 of file Error.h.
Function Documentation
template<typename... Args> void errorImpl (const char * file, size_t line, const char * func, const char * msg, Args... args)
Definition at line 26 of file Error.h.
References errorPass().
void errorOut (std::ostream & os, const char * v)
Definition at line 5 of file Error.h.
Referenced by errorPass().
template<typename T > void errorOut (std::ostream & os, T v)
Definition at line 10 of file Error.h.
template<typename T > void errorPass (std::ostream & os, T first)
Definition at line 15 of file Error.h.
References errorOut().
Referenced by errorImpl(), and errorPass().
template<typename T , typename... Args> void errorPass (std::ostream & os, T first, Args... args)
Definition at line 20 of file Error.h.
References errorOut(), and errorPass().