atwork-commander: /home/travis/build/steup/atwork-commander/atwork_commander_gen/src/ExampleNode.cpp File Reference
ExampleNode.cpp File Reference
#include <atwork_commander_gen/TaskGenerator.h>
#include <ros/ros.h>
#include <ros/console.h>
#include <exception>
#include <thread>
#include <chrono>
Functions
static void activateDebug ()
int main (int argc, char **argv)
Function Documentation
static void activateDebug () static
Definition at line 14 of file ExampleNode.cpp.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 21 of file ExampleNode.cpp.
References activateDebug(), atwork_commander::ConfigParserInterface::arena(), atwork_commander::TaskGenerator::check(), atwork_commander::TaskGenerator::config(), result, and atwork_commander::ConfigParserInterface::tasks().