atwork-commander: atwork_commander::task_generator Namespace Reference
atwork_commander::task_generator Namespace Reference
Namespaces
jurek
simple
Classes
class DefaultConfigParser
class GeneratorPluginInterface
struct Object
struct ObjectBase
struct ObjectType
struct Table
Typedefs
using Task = GeneratorPluginInterface::Task
using ObjectPtr = Object *
using ObjectTypePtr = ObjectType *
using TablePtr = Table *
Enumerations
enum Orientation : unsigned int { Orientation::HORIZONTAL, Orientation::VERTICAL, Orientation::FREE }
enum Type : unsigned int {
Type::UNKNOWN, Type::OBJECT, Type::COLORED_OBJECT, Type::CAVITY,
Type::CONTAINER
}
Functions
static bool readStrings (StringList &data, XmlRpc::XmlRpcValue &val)
static bool readStruct (ParameterType &params, XmlRpc::XmlRpcValue &val)
static TaskDefinition readTask (const std::string &name, XmlRpc::XmlRpcValue &def)
static TaskDefinitions readTaskList (const string &taskConfig)
static ArenaDescription readArenaDefinition (const string &arenaConfig)
static void filterObjects (TaskDefinitions &tasks, const ArenaDescription &arena)
Typedef Documentation
using atwork_commander::task_generator::ObjectPtr = typedef Object*
Definition at line 18 of file Generator.h.
using atwork_commander::task_generator::ObjectTypePtr = typedef ObjectType*
Definition at line 19 of file Generator.h.
using atwork_commander::task_generator::TablePtr = typedef Table*
Definition at line 20 of file Generator.h.
using atwork_commander::task_generator::Task = typedef GeneratorPluginInterface::Task
Definition at line 12 of file Generator.h.
Enumeration Type Documentation
enum atwork_commander::task_generator::Orientation : unsigned int strong
Enumerator
HORIZONTAL
Horizontal Orientation.
VERTICAL
Vertical Orientation.
FREE
Orientation to be chosen by the Team.
Definition at line 22 of file Generator.h.
enum atwork_commander::task_generator::Type : unsigned int strong
Enumerator
UNKNOWN
unknown object(invalid)
OBJECT
Plain Object without special properties.
COLORED_OBJECT
Colored Object.
CAVITY
PPT Cavity.
CONTAINER
Container(currently RED or BLUE)
Definition at line 28 of file Generator.h.
Function Documentation
static void atwork_commander::task_generator::filterObjects (TaskDefinitions & tasks, const ArenaDescription & arena) static
Definition at line 212 of file DefaultConfigParser.cpp.
References atwork_commander::ArenaDescription::objects.
Referenced by atwork_commander::task_generator::DefaultConfigParser::update().
static ArenaDescription atwork_commander::task_generator::readArenaDefinition (const string & arenaConfig) static
Definition at line 167 of file DefaultConfigParser.cpp.
References atwork_commander::ArenaDescription::cavities, atwork_commander::ArenaDescription::objects, atwork_commander::ArenaDescription::waypoints, and atwork_commander::ArenaDescription::workstations.
Referenced by atwork_commander::task_generator::DefaultConfigParser::update().
static bool atwork_commander::task_generator::readStrings (StringList & data, XmlRpc::XmlRpcValue & val) static
Definition at line 22 of file DefaultConfigParser.cpp.
Referenced by readTask().
static bool atwork_commander::task_generator::readStruct (ParameterType & params, XmlRpc::XmlRpcValue & val) static
Definition at line 46 of file DefaultConfigParser.cpp.
References result.
Referenced by readTask().
static TaskDefinition atwork_commander::task_generator::readTask (const std::string & name, XmlRpc::XmlRpcValue & def) static
Definition at line 66 of file DefaultConfigParser.cpp.
References atwork_commander::TaskDefinition::allowedTables, atwork_commander::TaskDefinition::cavities, atwork_commander::TaskDefinition::normalTableTypes, atwork_commander::TaskDefinition::objects, atwork_commander::TaskDefinition::parameters, atwork_commander::TaskDefinition::ppTypes, readStrings(), readStruct(), atwork_commander::TaskDefinition::shTypes, and atwork_commander::TaskDefinition::ttTypes.
Referenced by readTaskList().
static TaskDefinitions atwork_commander::task_generator::readTaskList (const string & taskConfig) static
Definition at line 137 of file DefaultConfigParser.cpp.
References readTask().
Referenced by atwork_commander::task_generator::DefaultConfigParser::update().