atwork-commander: atwork_commander Namespace Reference
atwork_commander Namespace Reference
Namespaces
com_plugin
task_generator
testing
Classes
struct ArenaDescription
Configuration Information for TaskGenerator representing Arena.
class ArenaVisGroup
Qt widget displaying task generator information.
class ConfigParserInterface
class Control
Interface class to the new RefBox of the @Work League.
class ControlError
Exceptions thrown by the Control interface of the refbox.
class ControlImpl
class MainVisGroup
The outer Widget managing all subGroups.
struct Object
struct ObjectBase
struct ObjectType
class RefboxUI
The Actual RVIZ Plugin.
class RobotVisGroup
Qt widget displaying robot information and control buttons.
class StateTracker
struct Table
struct TaskDefinition
Configuration Information for TaskGenerator representing specific task type.
class TaskGenerator
class TaskGenVisGroup
Qt widget displaying task generator information.
class TaskVirtualization
class VisGroup
Abstract Base Class VisGroup.
Typedefs
using State = atwork_commander_msgs::RefboxState
using RobotState = atwork_commander_msgs::RobotState
using RobotHeader = atwork_commander_msgs::RobotHeader
using Callback = Control::StateUpdateCallback
using StringList = std::vector< std::string >
List of character strings.
using ParameterType = std::unordered_map< std::string, int >
List of parameter key-value pairs.
using TaskDefinitions = std::unordered_map< std::string, TaskDefinition >
Definition of all available Tasks with the appropriate configuration parameters.
using ObjectPtr = Object *
using TablePtr = Table *
Enumerations
enum Orientation : unsigned int { Orientation::FREE, Orientation::VERTICAL, Orientation::HORIZONTAL }
enum Type : unsigned int {
Type::UNKNOWN, Type::OBJECT, Type::COLORED_OBJECT, Type::CAVITY,
Type::CONTAINER
}
Functions
template<typename T >
void call (string cmd, string service, T &arg)
static string genErrorMsg (string cmd, ControlError::Reasons reason, string argument)
template<typename T >
void errorOut (ostringstream &os, const T *v)
template<typename T >
void errorOut (ostringstream &os, T *v)
template<>
void errorOut (ostringstream &os, const char *v)
template<typename T >
void errorOut (ostringstream &os, T v)
template<typename T >
void errorPass (ostringstream &os, T first)
template<typename T , typename... Args>
void errorPass (ostringstream &os, T first, Args...args)
template<typename... Args>
void errorImpl (const char *file, size_t line, const char *func, const char *msg, Args...args)
Detailed Description
Todo:
write docs
Typedef Documentation
using atwork_commander::Callback = typedef Control::StateUpdateCallback
Definition at line 47 of file control.cpp.
using atwork_commander::ObjectPtr = typedef Object*
Definition at line 29 of file Generator.cpp.
using atwork_commander::ParameterType = typedef std::unordered_map<std::string, int>
List of parameter key-value pairs.
Definition at line 12 of file ConfigParserInterface.h.
using atwork_commander::RobotHeader = typedef atwork_commander_msgs::RobotHeader
Definition at line 33 of file atwork_refbox_ros_node.cpp.
using atwork_commander::RobotState = typedef atwork_commander_msgs::RobotState
Definition at line 32 of file atwork_refbox_ros_node.cpp.
using atwork_commander::State = typedef atwork_commander_msgs::RefboxState
Definition at line 31 of file atwork_refbox_ros_node.cpp.
using atwork_commander::StringList = typedef std::vector<std::string>
List of character strings.
Definition at line 11 of file ConfigParserInterface.h.
using atwork_commander::TablePtr = typedef Table*
Definition at line 30 of file Generator.cpp.
using atwork_commander::TaskDefinitions = typedef std::unordered_map<std::string, TaskDefinition>
Definition of all available Tasks with the appropriate configuration parameters.
Definition at line 67 of file ConfigParserInterface.h.
Enumeration Type Documentation
enum atwork_commander::Orientation : unsigned int strong
Enumerator
FREE
Orientation to be chosen by the Team.
VERTICAL
Vertical Orientation.
HORIZONTAL
Horizontal Orientation.
Definition at line 32 of file Generator.cpp.
enum atwork_commander::Type : unsigned int strong
Enumerator
UNKNOWN
unknown object(invalid)
OBJECT
Plain Object without special properties.
COLORED_OBJECT
Colored Object.
CAVITY
PPT Cavity.
CONTAINER
Container(currently RED or BLUE)
Definition at line 38 of file Generator.cpp.
Function Documentation
template<typename T > void atwork_commander::call (string cmd, string service, T & arg)
Definition at line 50 of file control.cpp.
Referenced by atwork_commander::ControlImpl::forward(), atwork_commander::ControlImpl::generate(), atwork_commander::ControlImpl::load(), atwork_commander::ControlImpl::start(), and atwork_commander::ControlImpl::stop().
template<typename... Args> void atwork_commander::errorImpl (const char * file, size_t line, const char * func, const char * msg, Args... args)
Definition at line 170 of file Generator.cpp.
References errorPass().
template<typename T > void atwork_commander::errorOut (ostringstream & os, const T * v)
Definition at line 139 of file Generator.cpp.
template<typename T > void atwork_commander::errorOut (ostringstream & os, T * v)
Definition at line 144 of file Generator.cpp.
template<> void atwork_commander::errorOut (ostringstream & os, const char * v)
Definition at line 149 of file Generator.cpp.
template<typename T > void atwork_commander::errorOut (ostringstream & os, T v)
Definition at line 154 of file Generator.cpp.
Referenced by errorPass().
template<typename T > void atwork_commander::errorPass (ostringstream & os, T first)
Definition at line 159 of file Generator.cpp.
References errorOut().
template<typename T , typename... Args> void atwork_commander::errorPass (ostringstream & os, T first, Args... args)
Definition at line 164 of file Generator.cpp.
References errorOut().
Referenced by errorImpl().
static string atwork_commander::genErrorMsg (string cmd, ControlError::Reasons reason, string argument) static
Definition at line 58 of file control.cpp.