atwork-commander: atwork_commander::testing::BasicControlTest Struct Reference
atwork_commander::testing::BasicControlTest Struct Reference
#include <BasicControlTest.hpp>
Public Member Functions
void SetUp () override
void expectReason (std::function< void()> func, ControlError::Reasons reason)
Static Public Member Functions
static std::string readRefboxName ()
Public Attributes
Control control
Detailed Description
Definition at line 15 of file BasicControlTest.hpp.
Member Function Documentation
void atwork_commander::testing::BasicControlTest::expectReason (std::function< void()> func, ControlError::Reasons reason) inline
Definition at line 32 of file BasicControlTest.hpp.
References atwork_commander::ControlError::reason().
static std::string atwork_commander::testing::BasicControlTest::readRefboxName () inline static
Definition at line 19 of file BasicControlTest.hpp.
Referenced by SetUp().
void atwork_commander::testing::BasicControlTest::SetUp () inline override
Definition at line 28 of file BasicControlTest.hpp.
References readRefboxName(), and atwork_commander::Control::refbox().
Referenced by ControlTests::SetUp().
Member Data Documentation
Control atwork_commander::testing::BasicControlTest::control
Definition at line 17 of file BasicControlTest.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_core/tests/src/BasicControlTest.hpp