atwork-commander: RefboxMockBase Struct Reference
RefboxMockBase Struct Reference abstract
Classes
class RefboxWrapper
Public Member Functions
virtual bool loadTask (LoadTask::Request &, LoadTask::Response &)=0
virtual bool stateChange (StateUpdate::Request &, StateUpdate::Response &)=0
virtual bool start (StartTask::Request &, StartTask::Response &)=0
virtual bool generate (GenerateTask::Request &, GenerateTask::Response &)=0
void periodic (const ros::TimerEvent &e)
bool loadTaskCall (LoadTask::Request &req, LoadTask::Response &res)
bool startCall (StartTask::Request &req, StartTask::Response &res)
bool stateChangeCall (StateUpdate::Request &req, StateUpdate::Response &res)
bool generateCall (GenerateTask::Request &req, GenerateTask::Response &res)
RefboxMockBase ()
void connect (const string &refbox)
void disconnect ()
virtual ~RefboxMockBase ()
Public Attributes
class RefboxMockBase::RefboxWrapper state
ros::Publisher statePub
ros::CallbackQueue queue
ros::ServiceServer loadSrv
ros::ServiceServer storeSrv
ros::ServiceServer stateChangeSrv
ros::ServiceServer startSrv
ros::ServiceServer generateSrv
ros::Timer timer
atomic< bool > stopped
thread run
Detailed Description
Definition at line 33 of file control.cpp.
Constructor & Destructor Documentation
RefboxMockBase::RefboxMockBase () inline
Definition at line 66 of file control.cpp.
virtual RefboxMockBase::~RefboxMockBase () inline virtual
Definition at line 118 of file control.cpp.
Member Function Documentation
void RefboxMockBase::connect (const string & refbox) inline
Definition at line 71 of file control.cpp.
References generateCall(), loadTaskCall(), periodic(), startCall(), and stateChangeCall().
Referenced by ControlTests::SetUp().
void RefboxMockBase::disconnect () inline
Definition at line 108 of file control.cpp.
Referenced by ControlTests::TearDown().
virtual bool RefboxMockBase::generate (GenerateTask::Request & , GenerateTask::Response &) pure virtual
bool RefboxMockBase::generateCall (GenerateTask::Request & req, GenerateTask::Response & res) inline
Definition at line 64 of file control.cpp.
References generate().
Referenced by connect().
virtual bool RefboxMockBase::loadTask (LoadTask::Request & , LoadTask::Response &) pure virtual
bool RefboxMockBase::loadTaskCall (LoadTask::Request & req, LoadTask::Response & res) inline
Definition at line 61 of file control.cpp.
Referenced by connect().
void RefboxMockBase::periodic (const ros::TimerEvent & e) inline
Definition at line 57 of file control.cpp.
Referenced by connect().
virtual bool RefboxMockBase::start (StartTask::Request & , StartTask::Response &) pure virtual
bool RefboxMockBase::startCall (StartTask::Request & req, StartTask::Response & res) inline
Definition at line 62 of file control.cpp.
References start().
Referenced by connect().
virtual bool RefboxMockBase::stateChange (StateUpdate::Request & , StateUpdate::Response &) pure virtual
bool RefboxMockBase::stateChangeCall (StateUpdate::Request & req, StateUpdate::Response & res) inline
Definition at line 63 of file control.cpp.
Referenced by connect().
Member Data Documentation
ros::ServiceServer RefboxMockBase::generateSrv
Definition at line 47 of file control.cpp.
ros::ServiceServer RefboxMockBase::loadSrv
Definition at line 47 of file control.cpp.
ros::CallbackQueue RefboxMockBase::queue
Definition at line 46 of file control.cpp.
thread RefboxMockBase::run
Definition at line 50 of file control.cpp.
ros::ServiceServer RefboxMockBase::startSrv
Definition at line 47 of file control.cpp.
class RefboxMockBase::RefboxWrapper RefboxMockBase::state
Referenced by ControlTests::toState().
ros::ServiceServer RefboxMockBase::stateChangeSrv
Definition at line 47 of file control.cpp.
ros::Publisher RefboxMockBase::statePub
Definition at line 45 of file control.cpp.
atomic<bool> RefboxMockBase::stopped
Definition at line 49 of file control.cpp.
ros::ServiceServer RefboxMockBase::storeSrv
Definition at line 47 of file control.cpp.
ros::Timer RefboxMockBase::timer
Definition at line 48 of file control.cpp.
The documentation for this struct was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_core/tests/src/control.cpp