atwork-commander: atwork_commander::task_generator::jurek::Converter Struct Reference
atwork_commander::task_generator::jurek::Converter Struct Reference
#include <TaskConverter.h>
Public Types
using Workstation = atwork_commander_msgs::Workstation
using Object = atwork_commander_msgs::Object
using Objects = vector< Object >
using WorkstationObjs = unordered_map< string, Objects >
using Workstations = vector< Workstation >
Static Public Member Functions
static bool compObjects (const Object &a, const Object &b)
static WorkstationObjs toMap (const Workstations &wsList)
static WorkstationObjs intersect (const WorkstationObjs &a, WorkstationObjs &b)
static WorkstationObjs diff (const WorkstationObjs &a, WorkstationObjs &b)
static string findObject (WorkstationObjs &wsMap, const Object &o, const string &source, bool del=false)
static int findContainer (const WorkstationObjs &wsMap, const Object &o, const string &source)
Detailed Description
Definition at line 16 of file TaskConverter.h.
Member Typedef Documentation
using atwork_commander::task_generator::jurek::Converter::Object = atwork_commander_msgs::Object
Definition at line 18 of file TaskConverter.h.
using atwork_commander::task_generator::jurek::Converter::Objects = vector<Object>
Definition at line 19 of file TaskConverter.h.
using atwork_commander::task_generator::jurek::Converter::Workstation = atwork_commander_msgs::Workstation
Definition at line 17 of file TaskConverter.h.
using atwork_commander::task_generator::jurek::Converter::WorkstationObjs = unordered_map<string, Objects>
Definition at line 20 of file TaskConverter.h.
using atwork_commander::task_generator::jurek::Converter::Workstations = vector<Workstation>
Definition at line 21 of file TaskConverter.h.
Member Function Documentation
static bool atwork_commander::task_generator::jurek::Converter::compObjects (const Object & a, const Object & b) inline static
Definition at line 23 of file TaskConverter.h.
static WorkstationObjs atwork_commander::task_generator::jurek::Converter::diff (const WorkstationObjs & a, WorkstationObjs & b) inline static
Definition at line 55 of file TaskConverter.h.
References result.
Referenced by atwork_commander::task_generator::jurek::Generator::fromTask().
static int atwork_commander::task_generator::jurek::Converter::findContainer (const WorkstationObjs & wsMap, const Object & o, const string & source) inline static
Definition at line 83 of file TaskConverter.h.
Referenced by atwork_commander::task_generator::jurek::Generator::fromTask().
static string atwork_commander::task_generator::jurek::Converter::findObject (WorkstationObjs & wsMap, const Object & o, const string & source, bool del = false) inline static
Definition at line 71 of file TaskConverter.h.
Referenced by atwork_commander::task_generator::jurek::Generator::fromTask().
static WorkstationObjs atwork_commander::task_generator::jurek::Converter::intersect (const WorkstationObjs & a, WorkstationObjs & b) inline static
Definition at line 39 of file TaskConverter.h.
References result.
Referenced by atwork_commander::task_generator::jurek::Generator::fromTask().
static WorkstationObjs atwork_commander::task_generator::jurek::Converter::toMap (const Workstations & wsList) inline static
Definition at line 27 of file TaskConverter.h.
References result.
Referenced by atwork_commander::task_generator::jurek::Generator::fromTask().
The documentation for this struct was generated from the following file:
/home/travis/build/steup/atwork-commander/atwork_commander_gen/src/jurek/TaskConverter.h