atwork-commander: /home/travis/build/steup/atwork-commander/atwork_commander_core/tests/src/control.cpp File Reference
control.cpp File Reference
#include "BasicControlTest.hpp"
#include <ros/callback_queue.h>
#include <ros/advertise_service_options.h>
#include <gmock/gmock.h>
#include <atwork_commander_msgs/LoadTask.h>
#include <atwork_commander_msgs/GenerateTask.h>
#include <atwork_commander_msgs/StartTask.h>
#include <atwork_commander_msgs/StateUpdate.h>
#include <thread>
#include <mutex>
#include <atomic>
Classes
struct RefboxMockBase
class RefboxMockBase::RefboxWrapper
struct RefboxMock
struct ControlTests
Typedefs
using AdSrvOpts = ros::AdvertiseServiceOptions
Functions
TEST_F (ControlTests, forwardFromFail)
TEST_F (ControlTests, forwardFromIdle)
TEST_F (ControlTests, forwardFromReady)
TEST_F (ControlTests, forwardFromPrep)
TEST_F (ControlTests, forwardFromExec)
TEST_F (ControlTests, forwardServiceError)
TEST_F (ControlTests, startFromFail)
TEST_F (ControlTests, startFromIdle)
TEST_F (ControlTests, startFromReady)
TEST_F (ControlTests, startFromPrep)
TEST_F (ControlTests, startFromExec)
TEST_F (ControlTests, startServiceError)
TEST_F (ControlTests, startSpecificRobot)
TEST_F (ControlTests, startMultipleRobots)
TEST_F (ControlTests, startInvalidRobot)
int main (int argc, char **argv)
Typedef Documentation
using AdSrvOpts = ros::AdvertiseServiceOptions
Definition at line 21 of file control.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 353 of file control.cpp.
TEST_F (ControlTests , forwardFromFail)
Definition at line 160 of file control.cpp.
References EXPECT_REASON.
TEST_F (ControlTests , forwardFromIdle)
Definition at line 166 of file control.cpp.
References EXPECT_REASON.
TEST_F (ControlTests , forwardFromReady)
Definition at line 172 of file control.cpp.
References EXPECT_REASON.
TEST_F (ControlTests , forwardFromPrep)
Definition at line 178 of file control.cpp.
TEST_F (ControlTests , forwardFromExec)
Definition at line 195 of file control.cpp.
TEST_F (ControlTests , forwardServiceError)
Definition at line 213 of file control.cpp.
References EXPECT_REASON.
TEST_F (ControlTests , startFromFail)
Definition at line 234 of file control.cpp.
References EXPECT_REASON.
TEST_F (ControlTests , startFromIdle)
Definition at line 240 of file control.cpp.
References EXPECT_REASON.
TEST_F (ControlTests , startFromReady)
Definition at line 246 of file control.cpp.
References start().
TEST_F (ControlTests , startFromPrep)
Definition at line 264 of file control.cpp.
References EXPECT_REASON.
TEST_F (ControlTests , startFromExec)
Definition at line 271 of file control.cpp.
References EXPECT_REASON.
TEST_F (ControlTests , startServiceError)
Definition at line 277 of file control.cpp.
References EXPECT_REASON, and start().
TEST_F (ControlTests , startSpecificRobot)
Definition at line 289 of file control.cpp.
References start().
TEST_F (ControlTests , startMultipleRobots)
Definition at line 315 of file control.cpp.
References start().
TEST_F (ControlTests , startInvalidRobot)
Definition at line 347 of file control.cpp.
References EXPECT_REASON.